### ISSUE TITLE
MAX - Object Tools - Materials section MultiMeshs

### ISSUE THREAD

**Issue by thor49** [TheGameCreators/GameGuruRepo#1090]
When you import multiMesh
 Multi-Texture models you get a DropListBox
with the meshs and access to individual Textures.
But in the Object tools Materials you
do not get the DropListbox to select all
the meshes and textures.

System Specs:
Operating System: Windows 10 Home 64-bit (10.0, Build 18363) (18362.19h1_release.190318-1202)
Language: English (Regional Setting: English)
System Model: All Series
Processor: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 CPUs), ~3.6GHz
Memory: 16384MB RAM
Windows Dir: C:\WINDOWS
DirectX Version: DirectX 12
Card name: NVIDIA GeForce RTX 2070
Dedicated Memory: 8031 MB
Current Mode: 1600 x 1200 (32 bit) (60Hz)
Card name: NVIDIA GeForce RTX 2070
Dedicated Memory: 8031 MB
Current Mode: 1280 x 1024 (32 bit) (60Hz)

**Comment by thor49** [comment]
Just to be clear the Importer part is OK ..
It is when you put your model in your level 
and you go to Object Tools - Materials.. there is no dropListBox to gain 
access to all the textures/meshes.. 
only one Texture set..

**Comment by LeeBamberTGC** [comment]
Will be sorted for this Friday build

**Comment by rvanner** [comment]
@thor49 Can you confirm this is now fixed for you please?

**Comment by thor49** [comment]
Hi RickYes 1090 has been fixed..thanks..
Any news on 1082 and 1085 .. half the models I have bought come in this category.. I bought quite a lot of FBX character models from cgTrader during the last 2 Black Friday sale periods..
Regardsthor49  ( J_C on the Game Creators forum)

    On Friday, 20 August 2021, 08:47:44 BST, Richard Vanner ***@***.***> wrote:  
 
 


@thor49 Can you confirm this is now fixed for you please?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by rvanner** [comment]
@thor49 OK I will close off this issue. The other issues still need investigating.
