### ISSUE TITLE
The fbx or x files imported via "import template..." to the classic game guru. downloaded from Steam on 06/2021 has an error. (item ceases to exist " when dragged to the map)?! {NOTE: error that does not occur in the trial version downloaded from the official website "on this date: 07/03/2021 which has the 2019 version, in the file with the date : 05/19/2020 11:47 AM}

### ISSUE THREAD

**Issue by Sr-Ivan** [TheGameCreators/GameGuruRepo#1224]

**Comment by plemsoft** [comment]
@Sr-Ivan Thanks for reporting this issue, this has been fixed and will be included in the next update :)

**Comment by Sr-Ivan** [comment]
plemsoft  - at your service
and what will be the next update date?
 for me to create items that I'm developing for free and to sell?
one more mistake for you: 
fbx items placed in game guru give tmb error (in third person mode), when the character approaches the walls!
in first person mode this does not happen!

**Comment by Sr-Ivan** [comment]
import problem. not resolved so far.
also "save standalone" when saving, saves to an empty map submerged in water, which is not the map I edited!!!
how can I activate the trial I downloaded from the site "game guru" with the Steam invoice?
because the trial version I downloaded doesn't have these import errors!
It remains to be seen if "save standalone" will work, because in the trial version it doesn't work!

**Comment by synchromesh62** [comment]
@Sr-Ivan 
If your standalone takes you to a map submerged in water its 99.9% because you are not saving your maps to the Default **mapbank** folder ... The 1% would be you forgot to put a start marker :) 

Make sure your maps are saved t the **mapbank** folder then try creating another standalone.

**Comment by Sr-Ivan** [comment]
with the "game guru trial" downloaded from the official website it is working correctly!
  it's just giving an error with the versions that steam is making available to me.
I'm saving correctly!
  " the trial version that I downloaded from the official site doesn't save but I believe it's because it's trial, but it doesn't give the import error.
will there be how do I activate the version I downloaded from the site with the proof of payment from steam?
to see if it exports the exe correctly.
I say this because it doesn't have the other FBX import errors so it should be without the other errors as well.
until last year i was exporting the game correctly this started this month from what i noticed.
the error persists in all the versions that steam makes available to me

**Comment by Sr-Ivan** [comment]
> @ Sr-Ivan
> Se o seu autônomo leva você a um mapa submerso na água, é 99,9% porque você não está salvando seus mapas na pasta do **banco de** mapas padrão ... O 1% seria que você esqueceu de colocar um marcador inicial :)
> 
> Certifique-se de que seus mapas sejam salvos na pasta do **mapbank** e tente criar outro autônomo.

about "save standalone", that's what you really guided me!
I was saving somewhere else! Haha ha
now I get it! :)
but the other problem is still not resolved.
"I'm glad the test version imports Fbx.
I'm making a move...
   importing in the test version and placing in the folder I bought in steam.
I believe it will work like this until the problem is fixed.
I have to fix now the errors that occur in the mesh of the items that are imported to the game guru.
thanks, so far :)

**Comment by Sr-Ivan** [comment]
> @Sr-Ivan
> If your standalone takes you to a map submerged in water its 99.9% because you are not saving your maps to the Default **mapbank** folder ... The 1% would be you forgot to put a start marker :)
> 
> Make sure your maps are saved to the **mapbank** folder then try creating another standalone.

synchromesh62 :
about "save standalone", that's what you really guided me!
I was saving somewhere else! Haha ha
now I get it! :)
but the other problem is still not resolved.
"I'm glad the test version imports Fbx.
I'm making a move...
importing in the test version and placing in the folder I bought in steam.
I believe it will work like this until the problem is fixed.
I have to fix now the errors that occur in the mesh of the items that are imported to the game guru.
thanks, so far :)

**Comment by Kitakazi** [comment]
This bug is still there but a quick work around is to open the FPE file for the entity and then add

model = dboname.dbo

where dboname is the name of the .dbo file of your model that is created when you complete and import. 
For w/e reason "model = x" is not added to the FPE files like it should be.
