### ISSUE TITLE
Warehouse Large Door has a messed up texture

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1277]
![image](https://user-images.githubusercontent.com/1503593/126493732-242760f7-b5aa-429f-851d-1d6c656cd289.png)

![image](https://user-images.githubusercontent.com/1503593/126493812-1cb80e46-6310-42b6-b42e-7298764a4d72.png)

**Comment by plemsoft** [comment]
This was already fixed in the latest version :)

**Comment by rvanner** [comment]
@plemsoft I am still seeing this issue. Do I need to clear the old thumbnail out?  

When I am not hovering over it I see this;
![image](https://user-images.githubusercontent.com/1503593/130759330-181f1f61-aebd-4957-8cd0-0ad8f00fcfe5.png)

Then when I hover over it, it's ok:
![image](https://user-images.githubusercontent.com/1503593/130759376-cb70f011-6592-4225-b4ed-b2f35783823e.png)

**Comment by rvanner** [comment]
@plemsoft This is still an issue for me. Maybe old data on my PC?

**Comment by plemsoft** [comment]
@rvanner Yes just use "update thumbnail" and it should be fine, the problem is that you have a old thumbnail in your write folder, so at some point you have generated a new thumb using the "bad" model :)
