### ISSUE TITLE
Saving your Map Progress Issue

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#1375]
Saving
When you have a map open and are wanting to save progress just Clicking "Save" does not seem to save the map but "Save As" and pointing to it does then seem to save it but you have to  do this every time for every map you work on.

**Comment by michaeloldman** [comment]
Yes, save has issues for quite some time now.
If you add stuff, then run the level to test, esc back to editor - you will have to click something in the editor before it will save changes.

If you add stuff run the level to test, esc back to editor, and then close the window with Top Right button it will close with no prompt to save.

**Comment by plemsoft** [comment]
@synchromesh62 This has been fixed and will be in the next update :)

**Comment by synchromesh62** [comment]
@plemsoft 
That appears to work now.
Thanks Preben

**Comment by michaeloldman** [comment]
@plemsoft mostly fixed for me

But still not reliably prompting to save if you close with Titlebar Button:
- Add entity
- run test game
- esc test game
- close window using window titlebar button
- MAX closes with no prompt to save changes

**Comment by plemsoft** [comment]
@michaeloldman Lee updated 1 hour ago, so should be fixed in a update later today :)
