### ISSUE TITLE
Autoflatten not saved 

### ISSUE THREAD

**Issue by ZakJudges** [TheGameCreators/GameGuruRepo#1785]
After placing a building down and saving:
![Screenshot 2022-01-17 125714](https://user-images.githubusercontent.com/32545391/149773801-3e7b450d-bfe5-477a-a88c-14093ec5a8ba.png)

After loading the same map, the flattened terrain is lost, but the grass is still removed:
![Screenshot 2022-01-17 125852](https://user-images.githubusercontent.com/32545391/149773926-4b3304e6-4f18-45f6-80c9-2f60656af864.png)

**Comment by ZakJudges** [comment]
Selecting the building will then flatten the terrain again

**Comment by UltraVox001** [comment]
I think autoflatten poses real problems : [video](https://i.gyazo.com/909b106acf3d8c5c41dfbe0efd7f9afa.mp4)

**Comment by plemsoft** [comment]
@PaulSJ I need a way to save flat areas , is there a way to do this ? , Let me know and i will add the actual loading and saving with the level , thanks :)

**Comment by UltraVox001** [comment]
@PaulSJ @plemsoft 
Please could you arrange that when the checkbox is disabled, Max remembers this setting on next reopening ?
Thank you...

**Comment by LeeBamberTGC** [comment]
@plemsoft Wioth the current system it is the object properties that is flagged as flatten which 'creates' the flat areas on the fly.  In this case there is no need to store a copy of the results of the flattening technique. As soon as the object causing the flatten is deleted, the flatten event is also removed. That is how it works now.

**Comment by UltraVox001** [comment]
@LeeBamberTGC 
The problem lies elsewhere. It's a matter of workflow (use) with the editor. I have several buildings which, when I select them, cause changes in terrain and vegetation. I have to deactivate this function in the editor, but each time I open it, I have to think about deactivating it.

**Comment by LeeBamberTGC** [comment]
@UltraVox001 In that case I have retagged this as a feature request to have more in-depth control of the flattening system. Right now for EA, it only has one purpose which is to flatten an area immediately beneath specific types of objects such as buildings and structures. You can switch this off and on per object, but that is the extent of the controls right now. If flatten mode is not to your liking you can switch this off when dropping in a new building, and flatten the area manually yourself.

**Comment by UltraVox001** [comment]
@LeeBamberTGC 
Where can I find this setting that allows this option to be disabled for my buildings ?
I did not find it. (except the box in the Settings).

**Comment by LeeBamberTGC** [comment]
@UltraVox001 Now that IS a good point :)  Right now you press the U key to toggle the auto flatten mode.

@plemsoft Much like you are doing with the I spray key, can you add U to the keyboard shortcuts and add a UI tick box to switch on and off the auto flatten feature. I think @rvanner needs to confirming this but I think it makes sense.

**Comment by plemsoft** [comment]
@LeeBamberTGC I fixed the original issue , flatten areas are now restored when loading the level.

@UltraVox001 Could you create a new "enhancement" request for a system to allow per object control of auto flatten, currently its global, when we have the per object control we can add keys like U to enable/disable flatten per object. Thanks :)

**Comment by plemsoft** [comment]
@LeeBamberTGC Auto flatten cant be restored the way it works now, when we load a level we cant restore autoflatten before the terrain is done creating (or autoflatten get incorrect height), a way to fix it could be to add auto flatten into GGTerrain_InvalidateRegion , so it also reset autoflatten areas, or have a command to convert autoflatten areas into heightmap data so the areas is saved with the level so we dont have to restore it, and would also allow users to use sculpt on the flatten area or terrain restore mode ?

**Comment by PaulSJ** [comment]
@plemsoft It should be possibel to add flat areas before the terrain is ready, the height will be set as NAN and then updated when the terrain is ready

**Comment by plemsoft** [comment]
@PaulSJ The loading of a map is a blocking process , so when you load a "flat" level , we setup the terrain and after that the objects and set add autoflatten , but at this point as the loading is blocking the terrain still have the old data (even if the terrain has been setup with the new terrain data) so the flatten areas get the height from the previous terrain , like in this screenshot at the top: https://github.com/TheGameCreators/GameGuruRepo/issues/2270#issue-1149755687
We do call at GGTerrain_InvalidateRegion ALL after the blocking "load" is done, but the flatten areas still use the old terrain height.

**Comment by PaulSJ** [comment]
Now that I think about it maybe the building should determine the height. 

I've committed a change to PJ-Branch4 that adds an additional parameter to GGTerrain_AddFlatRect, GGTerrain_AddFlatCircle, and GGTerrain_UpdateFlatArea that allow the caller to set the height. If not set then it behaves as it does now and lets the terrain set the height.

**Comment by LeeBamberTGC** [comment]
NOTE: Latest commits from this work are now in the master and the new internal build uploaded, though the new command behaviors are not integrated at this time in that build.

**Comment by plemsoft** [comment]
@PaulSJ It still do not work, it looks like it need ggterrain_local_params.height and the others, so i added:

`	else if (!isnan(height))
	{
		height -= ggterrain_local_params.offset_y;
		if (height < 0) height /= ggterrain_local_params.minHeight;
		else height /= ggterrain_local_params.height;
	}
`

But this dont solve it , as loading from one level at this point only the "ggterrain_global_params.height" have the correct  height, the "ggterrain_local_params.height" still have the old level height ?

**Comment by PaulSJ** [comment]
@plemsoft I've committed a change to PJ-Branch4 that makes the flat area height use the world value and only transition to terrain height when it is used

**Comment by LeeBamberTGC** [comment]
@PaulSJ Expect this in the build in 20 minutes

**Comment by PaulSJ** [comment]
@LeeBamberTGC @plemsoft Be careful of a conflict if both Preben and I have modified the process. Even if Github says there is no conflict it might have added both changes one after the other corrupting the flat area system.

**Comment by PaulSJ** [comment]
@LeeBamberTGC I took a quick look at the master branch and there was a conflict, I've commited a fix to master

**Comment by LeeBamberTGC** [comment]
@PaulSJ Many thanks, will upload the build soon.
