### ISSUE TITLE
SaveStandAlone Level Change Logic

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1819]
I made a 2 level game. 
Using Win Zones;
- Level 1 jumped to Level 2
- Level 2 jumped to Level 1

When running the game as a standalone, the game ended after level 2. It should have jumped back to level 1

**Comment by plemsoft** [comment]
@rvanner Thanks for reporting this issue, this was fixed in this Fridays build :)

**Comment by rvanner** [comment]
@plemsoft I just tried this and this time the first level just runs the first level again! So not fixed for me.

**Comment by plemsoft** [comment]
@rvanner did you export the standalone again ? , if so could you e-mail me the levels and storyboard so i can give it a try , thanks :)
