### ISSUE TITLE
MAX - 2022.02.04 - Change Outline Highlighter with Object Color Change

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#1923]
We used to be able to select objects easily - there are now several issues which make doing so very cumbersome
Here be another example
- Can not select large objects from inside - makes interior level editing a pain

https://youtu.be/4HZWTZ8roi4

**Comment by rvanner** [comment]
@OldFlak Are the issues in this report fixed now?

**Comment by OldFlak** [comment]
@rvanner Thanks for follow up :)
No issue is not fixed. Tis exactly the same as video in OP, except that now even the corner lights are not selectable either.

Finding same with many models even outside, almost as if you don't click on the point of origin for the model you can click till the cows come home and the object won't be selected.

Anything using transparency or Alpha Clip is the same - only real way to select them is with Detailed Objects List.

**Comment by rvanner** [comment]
@OldFlak Can you supply the level with the assets so Lee can load it in and see the same problems?

**Comment by LeeBamberTGC** [comment]
@rvanner This was a change we made so the user did not accidentally select the entire room they are in when moving objects about. Selecting an object "from inside" the object was disabled.  Should we add this back in, or add it via a tick box in developer mode so we protect new users and allow more expert users this freedom (and risk)?

**Comment by OldFlak** [comment]
**It makes sense to be able to select everything** - add a tick box to turn it off if you must. New users will not be that silly, and they ought to be taught properly how things work from the outset.

Making everything failsafe to **protect** new users is what has destroyed the MAX UI - give them some credit!
:) :) :)

**Comment by rvanner** [comment]
@LeeBamberTGC Yes I think a tick box would be the best option for now and put it in the Developer list under the Object Management Options. I think it can be OFF by default as OldFlak suggests. 

[ ] Stop objects from being moved when camera is inside them

Tip hint: "Tick this if you want to avoid selecting objects (eg buildings) when viewed inside of them"

**Comment by LeeBamberTGC** [comment]
@OldFlak Added for next build.

**Comment by OldFlak** [comment]
Thanks Lee - will test when it makes it to the MAX Updater :)

**Comment by OldFlak** [comment]
Works fine now thanks Lee :)
The only issue now is the confusion the outline of selected models creates - it is cool, but not really useful at all in complex scenes.

Why not remove the outline for selected models and change the color of the model instead like, Classic does.
