### ISSUE TITLE
MAX - Player moves veeeery slow going up/down slopes in some situations

### ISSUE THREAD

**Issue by fearlesswee** [TheGameCreators/GameGuruRepo#1927]
Title basically says it all; if you put down the "outdoor ramps" test asset in the MAX collection, try running up and down the stairs, at different angles, etc. Occasionally the player will rapidly lose speed and start slowing down to a painful crawl. Jumping doesn't change your speed, leading me to believe you're not getting "stuck", rather it might be some internal calculation that slows the player based on the slope(?), but something is going awry.

**Comment by UltraVox001** [comment]
Parlez-vous des escaliers de la collection Max ?
![Polygones](https://user-images.githubusercontent.com/96718175/152372615-d30c0a7d-0e06-4db6-b9d4-ac9743dea313.jpg)
Si c'est le cas, changez le mode de collision.
Utilisez Polygones. Il posera moins de problèmes que Hull Decomp.

**Comment by fearlesswee** [comment]
@UltraVox001 The issue happens on a number of slopes, and from what I can tell it seems to be unrelated to physics or "getting stuck" as you can freely jump; which if the issue was getting "stuck" this should free you and return you to normal speed, instead the player still moves at the same slow crawl mid-air. This all leads me to believe it must be some internal speed calculation based on slope in the player controller, and it's going awry.

**Comment by UltraVox001** [comment]
@fearlesswee 
Yes. This has happened to me before too :
- on the terrain (with nothing around)
- on an imported object
- on an object from Max with modified collisions.
We are like in a slow motion action. It is extremely unpleasant. This problem is difficult to reproduce, because the problem disappears at the next TestLevel. Then he reappears.

**Comment by rvanner** [comment]
@fearlesswee This should be fixed. Can you confirm?

**Comment by fearlesswee** [comment]
I'll test this in-depth tomorrow once I have time, but so far I have not noticed it occurring in normal play.

**Comment by fearlesswee** [comment]
I've tested this using the same methods as before, and so far I think it's been dealt with. There might be some edge cases where this could still occur but I'll re-open this if I notice it.
