### ISSUE TITLE
MAX - 2022.02.18 - Transparent Objects Not Casting Shadows

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#2143]
In earlier versions the text on this glass would be cast onto the wall behind
- somewhere along the line we have lost that ability

![image](https://user-images.githubusercontent.com/12246318/154253219-05d7974b-da22-46fb-831a-2c6ea30cb4a0.png)

**Comment by OldFlak** [comment]
@LeeBamberTGC  Thanks Lee for responding. 

It is indeed a resource thing, but also should be a dev choice. 

In most cases it would need to be turned off for sure, but there are times when there is little impact on a scene, and can be used to good effect to make a scene pop, and in some cases - like in my pic - it stands out as wrong when it is not casting the shadow.

Yes off switch please :) - that would be way to go.

**Comment by LeeBamberTGC** [comment]
@PaulSJ I think you were the original proponent of switching off shadows for transparency. Is the code still there, and perhaps we can reactivate but have the default as OFF :)

**Comment by plemsoft** [comment]
@PaulSJ I then also need to split shadows for transparent, so i will enable it when i have split out the transparent shadows :)

**Comment by plemsoft** [comment]
@OldFlak Thanks for reporting this issue, this has been fixed and now have a checkbox on/off , ready from the next build :)

**Comment by OldFlak** [comment]
@plemsoft Hi Preben thanks for looking at this. Just tried in todays build but still not working.
If you enable shadows on the object - it gets disabled again when you run test-game.

**Comment by plemsoft** [comment]
@OldFlak Yes sorry there was some other issues with transparent shadows that was fixed this morning , so you have to wait until next update to test :)

**Comment by OldFlak** [comment]
@plemsoft Hi Preben thanks for looking at this issue.

I am struggling to see why we need another obscure setting for this - why would you want it to be a universal setting, surely it needs to remain a per object setting.

It worked fine using the properties settings to enable shadows on a per object basis, why not just put it back the way it was :)

Changes like these just make simple things more complicated, and or remove design choices from the dev
- but it won't stop bad performance on poorly designed and unoptimized games

On a side note nothing cast shadows now unless that setting is checked - so it is now all or nothing?

**Comment by plemsoft** [comment]
@OldFlak "On a side note nothing cast shadows now unless that setting is checked - so it is now all or nothing?" No it was a bug that has been fixed.

Transparent shadows has been separated from normal shadows to save GPU memory , actually transparent shadows use way more GPU mem then the normal shadows, that's also why it will be off by default. Anyway as i said the problems with separating the shadows has been fixed and will be in the next update, so you can test it, like it was supposed to work, thanks for your help :)

**Comment by LeeBamberTGC** [comment]
Will be in new internal build in about 15 minutes.

**Comment by OldFlak** [comment]
Thanks Lee and Preben

We obviously wouldn't want to have all transparent objects casting shadows perhaps one or two.

So we can still turn shadows off on each transparent object if we want?

**Comment by OldFlak** [comment]
@plemsoft Thanks again for looking at this - can't believe I create so much work for you :)

All other shadows are working now - thanks.

Still cant get transparency on the glass like before
- it seams to caste the whole object - not casting shadow of text like in earlier versions (could just be in editor tho)
- when running test game it disables the setting so can't in runtime

https://youtu.be/9GeNEj2P5qQ

Also have enabled Transparent shadows in Shadows tab :)

**Comment by OldFlak** [comment]
Just reporting back to say this issue is still not sorted...

The text on this panel in below pic used to cast a shadow on wall.
The Cast Shadows checkbox in properties is now being retained, and as shown in below pick Transparent Shadows is also checked.
![image](https://user-images.githubusercontent.com/12246318/163180799-412f3ded-c863-4eae-bd1b-9a23348a46ba.png)

**Comment by LeeBamberTGC** [comment]
@OldFlak Latest EXP build has a tick box to activate this feature at a small performance hit:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/44c4cfae-0f69-4ff4-b12d-7692fca622aa)

**Comment by OldFlak** [comment]
Hi Lee - thanks for getting back.
Yes the Tickbox for shadows has been there for some time - but it doesn't work as noted in my replies above to Preben.

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/12246318/27f6b71d-744d-4415-a8f8-7b3a01c357d9)
Notice the shadow of the glass is as if it was solid object - previously it would reflect the text on the wall as well

**Comment by LeeBamberTGC** [comment]
@OldFlak I don't think we have any semi-transparent glass with solid text in the texture. Can you email me your CARTOGRAPHY sign and I will make sure it works when you set transparent shadows on. Thanks!

**Comment by OldFlak** [comment]
Thanks again Lee - email sent :)

**Comment by LeeBamberTGC** [comment]
@OldFlak I was able to reproduce in a way, the shadow is not like before but somehow taking the colors of the semi-transparent material into account. Not sure if that is what works best as before I am sure it was just taking the alpha as the blocking info:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/654872ce-92e5-4427-bb1f-821be0bff14d)

I will look at this and get back to you, may be two options, or just restoring to the alpha method would be best for now and the 'colored stained glass shadow' effect can be a feature request for when the bugs are done.

**Comment by OldFlak** [comment]
Yep could be a new feature!

Thanks for looking at this Lee - but tis not a crucial element - would rather you get projects in, then come back to it in the future :)

**Comment by LeeBamberTGC** [comment]
@OldFlak Too late, I was already working on the problem when you posted :)  Now uses the greyscale alpha method, and looks much nicer:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/679a1493-5f1c-46d7-9c49-7addaaf4236c)

I also added a clip that should speed up ALL transparent shadows when ticked too :)

**Comment by Granada1** [comment]
Great fix Lee  👍

**Comment by OldFlak** [comment]
Lee!  Awesome!

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/12246318/1b73d16a-eb26-4dc9-af19-f8a21bd96987)

Thanks Lee - you the man :)

Another bug bites the dust...
