### ISSUE TITLE
MAX - 2022.02.25 - Scale For Objects Is Broken

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#2316]
Add entities - position them, and run level - all good

![image](https://user-images.githubusercontent.com/12246318/155867714-c7ddde32-c295-4f6c-b723-f4bb17844d9e.png)

Save level, close/open MAX, load level - Scale huge

![image](https://user-images.githubusercontent.com/12246318/155867726-e26773bb-b95e-46c9-8a02-13c7718ab17a.png)

Might be an idea to have a good look at the way max stores and retrieves settings - it constantly has one issue after another :)

**Comment by UltraVox001** [comment]
I confirm this bug.
![Big](https://user-images.githubusercontent.com/96718175/155877374-5d33e2d7-d36f-421d-ba21-deb0365d78ba.jpg)

**Comment by AmenMoses** [comment]
Any chance of fixing #2279? @plemsoft

**Comment by UltraVox001** [comment]
@plemsoft 
Just a side note : even some Lights get huge in the Editor. This happens at the end of a save in Max.
![BigLights](https://user-images.githubusercontent.com/96718175/155884507-f0d572dd-4e59-4389-8e23-506f9a79c3dd.jpg)

**Comment by davekirk85** [comment]
I've just started getting the issue also, so frustrating :/

**Comment by davekirk85** [comment]
struggling with the same issue still 
![ggmax error2](https://user-images.githubusercontent.com/100531173/155895065-9c80523d-ee4c-4ef4-87ee-0c4739a66cd3.JPG)
![ggmax error](https://user-images.githubusercontent.com/100531173/155895066-5618484a-b3e4-4960-bbed-25482b88b096.JPG)

**Comment by davekirk85** [comment]
if i create a level now, will the objects be resized automatically on the next update or will i need to manually do all the objects?

**Comment by 3coms** [comment]
https://youtu.be/Jo16FUdPohA

**Comment by OldFlak** [comment]
@plemsoft Hi Preben fyi issue is fixed in current build

**Comment by davekirk85** [comment]
@[OldFlak I still get the issue on the latest build

**Comment by UltraVox001** [comment]
Me too. Same problem.

**Comment by OldFlak** [comment]
@LeeBamberTGC fixed for me in 2022.03.04

**Comment by UltraVox001** [comment]
Fixed now

**Comment by LeeBamberTGC** [comment]
@OldFlak Thanks for confirming your issue is fixed, I will close this issue and recommend @davekirk85 and @UltraVox001 create their own issue if they find another scenario involving scale with the current internal build from this week fails.

**Comment by 3coms** [comment]
> @OldFlak Thanks for confirming your issue is fixed, I will close this issue and recommend @davekirk85 and @UltraVox001 create their own issue if they find another scenario involving scale with the current internal build from this week fails.

I already did so, but my thread is closed by someone, and my issue is still there; it happens to me in the very latest build.

**Comment by davekirk85** [comment]
I am still having the same issue on the latest build

**Comment by davekirk85** [comment]
@LeeBamberTGC 
"I have uploaded the internal build now so can be tested by @davekirk85 and @UltraVox001"
How do i access this build? I only have options to verify/update to the 25/02 build
