### ISSUE TITLE
Max Bug ?- spotlight rotation problem

### ISSUE THREAD

**Issue by bluemeenie195** [TheGameCreators/GameGuruRepo#2468]
Don't know if this is cause of some new lua command or a bug, but when using the light_npc script that locks a spotlight to a moving entity, the spotlight will spin like a top depending on what direction the entity goes.
In GG classic this does not happen

https://www.youtube.com/watch?v=xiP2tLIekR8

[light_npc.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8225450/light_npc.zip)

**Comment by dllllllllllb** [comment]
@bluemeenie195 The video you linked is unavailable, can you please send us a working link or upload the video directly to GitHub :]

**Comment by AmenMoses** [comment]
Drop a light in and change to spotlight, note that the light directing is straight down to the ground.
Light entity angles are 90, 45, 0 and light direction vector is -0.5, -0.75, -1  (which is not a normalised vector!)
Rotate light entity so hat light direction is straight 'north' (+Z direction)
Light entity angles are 180, 0, 180, light direction vector is -1, 0, -1 
Light entity facing south give angles of 0, 0, 0 with direction vector of -1, -1, -1

Makes no sense at all to me!  None of my light direction scripts that work fine in GG work in MAX.

**Comment by bluemeenie195** [comment]
Link is fixed. Thanks

**Comment by LeeBamberTGC** [comment]
@bluemeenie195 Seems fixed in latest EXP build, can you confirm:
![image](https://user-images.githubusercontent.com/35840583/230146170-658f9980-744c-4438-a27f-7bda67a76f63.png)

**Comment by bluemeenie195** [comment]
Unfortunately, going by the AmenMoses script I am using still doesn't work.
The spotlight should lock in place, but will always turn around and point at the npc. even a regular light will go behind the npc even though I put the light in front of the npc.
[light_npc.zip](https://github.com/TheGameCreators/GameGuruRepo/files/11170446/light_npc.zip)

**Comment by bluemeenie195** [comment]
I will. thank you

**Comment by AmenMoses** [comment]
#ifdef WICKEDENGINE
		//PE: Range -1 to 1.0 , convert to 0-360.
		//PE: This makes it rotate like in Classic.
		t.infinilight[i].f_angle_x = (t.infinilight[i].f_angle_x + 1.0) * 180.0;
		t.infinilight[i].f_angle_y = (t.infinilight[i].f_angle_y + 1.0) * 180.0;
		t.infinilight[i].f_angle_z = (t.infinilight[i].f_angle_z + 1.0) * 180.0;
		#endif

There's your problem.

The inputs from the Lua function are not angles, they are a vector!

So this isn't going to work, converting from vector to separate angles is going to involve a bit of trigonometry methinks.

**Comment by LeeBamberTGC** [comment]
@AmenMoses Yes the command name is a little misleading. The instructions are in global.lua but I agree not many read those: 

SetLightAngle : SetLightAngle( lightNum, xv, yv, zv ) -- set a vector (-1 to 1) to each angle which is then converted to 0-360

I have added a new command for the next EXP build:

GetLightEuler : GetLightEuler ( lightNum, x, y, z ) -- get the euler angles from the light direction
SetLightEuler : SetLightEuler( lightNum, x, y, z ) -- set euler angles for the light direction

**Comment by LeeBamberTGC** [comment]
function RotateLight_main(e)
 if module_lightcontrol.control(e) == 1 then
  local useeulerangle = 1
  if useeulerangle == 1 then
   -- using direction euler
   if g_lightrotate[e]['anticlockwise'] == 0 then
    g_lightrotate[e]['angle']=g_lightrotate[e]['angle']+(g_lightrotate[e]['speed']/20.0)
   else
    g_lightrotate[e]['angle']=g_lightrotate[e]['angle']-(g_lightrotate[e]['speed']/20.0)
   end
   if g_lightrotate[e]['angle'] >= 360.0 then g_lightrotate[e]['angle'] = g_lightrotate[e]['angle'] - 360.0 end
   if g_lightrotate[e]['angle'] < 0.0 then g_lightrotate[e]['angle'] = g_lightrotate[e]['angle'] + 360.0 end
   local lightNum = GetEntityLightNumber( e )
   x, y, z = GetLightEuler(lightNum)
   local vectory = g_lightrotate[e]['angle']
   SetLightEuler(lightNum,x,vectory,z)
  else
   -- using direction vector
   if g_lightrotate[e]['anticlockwise'] == 0 then
    g_lightrotate[e]['angle']=g_lightrotate[e]['angle']+(g_lightrotate[e]['speed']/3600.0)
   else
    g_lightrotate[e]['angle']=g_lightrotate[e]['angle']-(g_lightrotate[e]['speed']/3600.0)
   end
   if g_lightrotate[e]['angle'] > 1.0 then g_lightrotate[e]['angle'] = g_lightrotate[e]['angle'] - 2.0 end
   if g_lightrotate[e]['angle'] < -1.0 then g_lightrotate[e]['angle'] = g_lightrotate[e]['angle'] + 2.0 end
   local lightNum = GetEntityLightNumber( e )
   x, y, z = GetLightAngle(lightNum)
   local vectory = g_lightrotate[e]['angle']
   SetLightAngle(lightNum,x,vectory,z)
  end
 end
end

**Comment by AmenMoses** [comment]
@LeeBamberTGC So have you fixed the dodgy code I posted above?

I have a workaround in Lua but it would be much more efficient to do it in properly the engine.

The work around:  (given the vector values being in dirVec, nullVec is simply (x = 0, y= 0, z = 1) )

		-- convert from vector to weird angle format due to MAX bug
		-- Hopefully when MAX is fixed properly this can simply be commented out.
		local quat = V.QuatBetween( nullVect, dirVec)
		local vax, vay, vaz = Q.ToEuler( quat )
		dirVec.x = deg( vax ) / 180.0 - 1;
		dirVec.y = deg( vay ) / 180.0 - 1;
		dirVec.z = deg( vaz ) / 180.0 - 1;

		SetLightAngle( light.Id, dirVec.x, dirVec.y, dirVec.z )

**Comment by AmenMoses** [comment]
So any legacy scripts will have to be rewritten to use the new commands if users need them to work?  Seems like a strange approach to take!

At least change global.lua documentation of all the no-longer working functions so people don't spend hours tearing their hair out thinking they are doing something wrong when in reality the commands are broken!

**Comment by LeeBamberTGC** [comment]
@AmenMoses If you mean Classis scripts, they are not 100% forward-compatible with MAX.  Which legacy scripts are you referring to, can you attach and example, thanks!

Also, if you find any commands in global.lua that are broken, or absent in MAX, let me know here and I will update.
