### ISSUE TITLE
GG Max crashes loading level editor

### ISSUE THREAD

**Issue by AvengingEagle** [TheGameCreators/GameGuruRepo#2586]
Windows 10 professional 64-bit
CPU: Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz 
RAM: 16GB
GPU: Nvidia GeForce GTX 1050Ti

Max version: 2022.03.18

Downloaded Max for the first time yesterday and it opened fine, spent 10 minutes playing but decided to hold off until the new update released that evening. But today, following the latest update, it won't get past the storyboard editor or terrain generator without crashing. 

Try to play a demo game: crash
Try to edit a level: crash
Try to generate terrain and open editor: crash

I've tried reinstalling from scratch, to no avail. I've also tried running as administrator. 

https://www.youtube.com/watch?v=7ZnrpzeL5I0

**Comment by thecyrus** [comment]
Same here, since the last update I can't load or play any level.

**Comment by oldgamr** [comment]
I am having the same issue. Started happening after update.
I can't load my own maps or the demos. Crashes at the same spot.

**Comment by ivanski1983** [comment]
Wonder if its related. I have the same issue but it started with the previous build. Issue #2505. I started another level just to create buildings and now I cannot edit that level too.

**Comment by Ratall** [comment]
I can not create a level when I click generate terrain i just crashes could this be related

**Comment by Ratall** [comment]
I removed GGMax completely and reinstalled. Now it will not run at all. It just dies after the flash screen.
It appears to die CREATING P-LIST though this may be a new problem, As I forgot to check the log during the previous problem my apologies.

[Guru-MapEditor.log](https://github.com/TheGameCreators/GameGuruRepo/files/8313364/Guru-MapEditor.log)
.

**Comment by PaulSJ** [comment]
Weirdly it all works here. If you rename or delete the file at "Max\Files\gamecore\projectiletypes\TracerParticle.dbo" does the log show it getting any further?

If so then something in the projectiletypes folder is causing a problem. You can try removing folders to see if you can nail down which one it is (renaming won't work they have to be deleted so just backup the folder somewhere else before doing this).

**Comment by AvengingEagle** [comment]
Deleted TracerParticle.dbo, tried running again. Loaded the terrain generator, made two small tweaks, then clicked generate terrain and open the level editor and it crashed to desktop again.

[Guru-MapEditor.log](https://github.com/TheGameCreators/GameGuruRepo/files/8316299/Guru-MapEditor.log)

**Comment by PaulSJ** [comment]
Can you zip up your Max\Files\gamecore\projectiletypes folder and send it to me?

**Comment by AvengingEagle** [comment]
@PaulSJ 
[projectiletypes.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8316866/projectiletypes.zip)

**Comment by thecyrus** [comment]
My debugger blames assimp.dll.

Ecception not handled in 0x00007FF9CF886C34

**Comment by PaulSJ** [comment]
Unfortunately I can't see anything in the folder that would cause the crash, nor why assimp would be crashing since that hasn't changed in awhile. You can try replacing your Max/GameGuruMAX.exe file with the one from here https://drive.google.com/file/d/1ov4IqubcnVZ6h5dtJUZGz1NpISAbRxZi/view?usp=sharing and seeing if that changes anything

**Comment by LeeBamberTGC** [comment]
@PaulSJ I committed a fix a few hours ago that 'would' crash sometimes if the level contained a smart object (like the candle in the cellar demo), fixed for the current internal build.

**Comment by ivanski1983** [comment]
I swapped in the new .exe and I still have the same crashes

[dxdiagreport.txt](https://github.com/TheGameCreators/GameGuruRepo/files/8327578/dxdiagreport.txt)

**Comment by LeeBamberTGC** [comment]
@ivanski1983 Alas looks like the "NVIDIA GeForce GTX 970M" is below our minimum specifications for the EA release.

**Comment by AvengingEagle** [comment]
I'm on a GTX 1050Ti, which is not. Seems strange several people are reporting the same or similar issues but you can't replicate it. Once I have more time, I'll investigate further and try to provide more info on the specific crashes I'm experiencing. 

I tried your EXE, Paul, but sadly it made no difference.

**Comment by ivanski1983** [comment]
![F67FAEEB-3A61-41A3-85C3-2C1CF22D166F](https://user-images.githubusercontent.com/78671386/159579318-155104da-2dac-418e-9960-6c28ae03db9f.png)

**Comment by LeeBamberTGC** [comment]
@dllllllllllb Can you find out who "PCGAMEBENCHMARK.COM" are and how they are able to state what MAX min requirements are, thanks!

**Comment by Ratall** [comment]
I have downloaded again and original problem back as it does not want to run the terrain editor and will not generate terrain etc tried the new exe no change
I have included the dxdiag and  the log files
[dxdiagreport.txt](https://github.com/TheGameCreators/GameGuruRepo/files/8328266/dxdiagreport.txt)
[Guru-MapEditor.log](https://github.com/TheGameCreators/GameGuruRepo/files/8328267/Guru-MapEditor.log)
[Guru-Game.log](https://github.com/TheGameCreators/GameGuruRepo/files/8328276/Guru-Game.log)

**Comment by synchromesh62** [comment]
> @dllllllllllb Can you find out who "PCGAMEBENCHMARK.COM" are and how they are able to state what MAX min requirements are, thanks!

Sorry Lee took a quick Gander ..
Looks like its comparing Steam Specs to the users machine specs when it scans or whatever it does.
![specs](https://user-images.githubusercontent.com/35708217/159593126-3aa9b104-0382-4d9a-8654-1bc3c6598d8a.png)

**Comment by AvengingEagle** [comment]
Right. I did some more tests, recorded my screen each time, and saved the applicable log file. 

Crash 1: Trying to play a demo level
[Video](https://youtu.be/czpVmMsqB6A)
[Guru-Game.log](https://github.com/TheGameCreators/GameGuruRepo/files/8328538/Guru-Game.log)
[Guru-MapEditor.log](https://github.com/TheGameCreators/GameGuruRepo/files/8328539/Guru-MapEditor.log)

Crash 2: Trying to edit a demo level
[Video](https://youtu.be/-Ca5Yn66K1w)
[Guru-MapEditor.log](https://github.com/TheGameCreators/GameGuruRepo/files/8328564/Guru-MapEditor.log)

Crash 3: Trying to generate a terrain and open the editor
[Video](https://youtu.be/qyO-PH0p8gA)
[Guru-MapEditor.log](https://github.com/TheGameCreators/GameGuruRepo/files/8328563/Guru-MapEditor.log)

I hope these shed more light on my issues.

**Comment by PaulSJ** [comment]
Can you try the following EXE https://drive.google.com/file/d/1CwmoKM5B9MyqdqCeMTJXijSgpPg191bc/view?usp=sharing it removes some SSE instructions we were using

**Comment by GraPhiX-Guru** [comment]
I have had a similar issue and fixed mine. not sure if it will help any of you but worth a try none the less
https://github.com/TheGameCreators/GameGuruRepo/issues/2610

**Comment by AvengingEagle** [comment]
@PaulSJ Still crashed for me but I'm now verifying my files and will try a clean installation of my graphics drivers like GraPhiX suggested.

**Comment by rvanner** [comment]
@AvengingEagle If you can get back to us today with your latest findings that would be great. We are keen to learn why you're seeing this all of a sudden.

**Comment by GraPhiX-Guru** [comment]
Just another test i have done, my laptop had the same drivers 511.** and the same issue occurred, this time i tried something different, i left my Nvidia drivers alone, uninstalled MAX (completely) deleted the writable folder also, re installed MAX ran the demos and they worked fine, i then recreated my test level from scratch and that also ran fine ! restored my previous test level from a backup dropped it into the writable area and it crashes MAX when i run it, went back to the new level i created and it worked fine.
So all i can assume is any level built prior to this release of MAX may cause issue if you try to run it

**Comment by PaulSJ** [comment]
@GraPhiX-Guru Can you send me the old level that crashes? That might reveal something about these other crashes

**Comment by GraPhiX-Guru** [comment]
@PaulSJ sure here ya go, it was nothing special just a test
[Default.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8332471/Default.zip)

**Comment by GraPhiX-Guru** [comment]
oh here is the project file too
[projectbank.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8332527/projectbank.zip)

**Comment by GraPhiX-Guru** [comment]
Just a FYI i have now updated to 512.** on my laptop and my old level loads go figure

**Comment by PaulSJ** [comment]
Thanks, unfortunately I can't see anything out of the ordinary so it is a mystery why that version of the driver failed in some cases

**Comment by GraPhiX-Guru** [comment]
@PaulSJ  roughly around the 7th March some fake Nvidia drivers were doing the rounds, i hope it as nothing to do with this.
I would advise anyone with Nvidia cards to download the latest drivers directly from Nvidia.
link to the news https://www.pcinvasion.com/nvidia-data-breach-malware-gpu-drivers/

**Comment by PaulSJ** [comment]
@AvengingEagle Can you try this debug version https://drive.google.com/file/d/13sUz32VZHmxbT-hHifHvcczNOefsS8Eb/view?usp=sharing it will be a lot slower but should hopefully give you an error message instead of a crash

**Comment by AvengingEagle** [comment]
@PaulSJ Downloaded the EXE you provided and replaced the original EXE with it, and popped the DLLs in the same folder, next to the EXE. 

Tried playing River Raiders, it crashed to desktop with no error code.
[Guru-Game.log](https://github.com/TheGameCreators/GameGuruRepo/files/8335952/Guru-Game.log)
[Guru-MapEditor.log](https://github.com/TheGameCreators/GameGuruRepo/files/8335953/Guru-MapEditor.log)

**Comment by AvengingEagle** [comment]
This, from dxdiag:

Windows Error Reporting:
+++ WER0 +++:
Fault bucket 1542470055435017530, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: GameGuruMAX.exe
P2: 0.0.0.0
P3: 623b06c5
P4: assimp.dll
P5: 5.0.1.0
P6: 60951b5e
P7: c0000005
P8: 0000000000116c34
P9: 
P10:

**Comment by PaulSJ** [comment]
@AvengingEagle Do you happen to have GameGuruMAX installed at "E:\Programs\GameGuruMAX"? As that happens to be exactly where I have it installed, so I'm just wondering if it is a coincidence or if my path has somehow been baked into the executable

**Comment by AvengingEagle** [comment]
@PaulSJ Yes that's exactly where it's installed for me too :)

**Comment by PaulSJ** [comment]
Cool, at least that's one thing I can rule out.

Could you try using this executable https://drive.google.com/file/d/1DskShcbg5yzb-EpwVORszTDHjRD533GU/view?usp=sharing it will write to the log file the path of every entity it tries to load, hopefully that will reveal something

**Comment by Ratall** [comment]
Ran it with your extra logging
[Guru-Game.log](https://github.com/TheGameCreators/GameGuruRepo/files/8338245/Guru-Game.log)
[Guru-MapEditor.log](https://github.com/TheGameCreators/GameGuruRepo/files/8338247/Guru-MapEditor.log)

**Comment by AvengingEagle** [comment]
@PaulSJ This is what I got when I tried to play 'River Raiders' from the demos menu: 
[Guru-Game.log](https://github.com/TheGameCreators/GameGuruRepo/files/8339609/Guru-Game.log)

I then tried to edit River Raiders, resulting in insta-crash and this log:
[Guru-MapEditor.log](https://github.com/TheGameCreators/GameGuruRepo/files/8339634/Guru-MapEditor.log)

Both times it appears to crash loading a military hanger? So I decided to pick a map that didn't have that hanger in it (Escape of The Zombie Cellar) and try editing that.
[Guru-MapEditor.log](https://github.com/TheGameCreators/GameGuruRepo/files/8339654/Guru-MapEditor.log)

And here's what I get when I try to generate terrain on a new map and open the editor:
[Guru-MapEditor.log](https://github.com/TheGameCreators/GameGuruRepo/files/8339674/Guru-MapEditor.log)

**Comment by PaulSJ** [comment]
Thanks both of you for the logs, it looks like it is trying to load an empty path, but I'm not sure how that's happening when it's fine for us. Can you try this version and see if it fixes the problem https://drive.google.com/file/d/1ATOJsaeB8PY8jmmW1EOGQD8ab9kmdleI/view?usp=sharing

**Comment by Ratall** [comment]
That seemed to fix it.
[Guru-MapEditor.log](https://github.com/TheGameCreators/GameGuruRepo/files/8340914/Guru-MapEditor.log)
I included the log so you could check if it worked as expected.

**Comment by AvengingEagle** [comment]
It runs! Performance isn't great but that's a different issue. Thanks Paul!
