### ISSUE TITLE
GameGuru MAX - Bug - "Screens" and Ultrawide Monitors Issue

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#2719]
For those of us that have ultrawide monitors, the "screens" (Splash screen, Title screen, Loading screen, etc.) present a bit of an issue. They stretch, are ugly as a result, and text gets cut off so we can't read it. That means that if we were to ship a game and someone were to play it on an ultrawide monitor, they would not be happy with what they see. Here's an example from one of the demos, Foggy Forest:

This is what I see in the Storyboard editor:
![ultra1](https://user-images.githubusercontent.com/36735507/161139574-59b54b1b-9c8a-4493-8e4f-7a801b1c5ffd.png)

And this is what I see when I run the game:
![ultra2](https://user-images.githubusercontent.com/36735507/161139608-6d8340f6-66a2-466f-b01b-ee608989a57b.png)

My screen resolution is 3440 x 1440. Some even have a wider resolution and, as a result, I am sure these "screens" look even worse. 

MAX needs a way to detect what resolution the system is running at and adjust these screens accordingly. For widescreens and ultrawides, this typically means ensuring they fill the screen vertically and inserting black bars to fill the leftover space left and right horizontally:

![ultra3](https://user-images.githubusercontent.com/36735507/161140111-ce5b2b58-9267-4dc5-b5e2-cf2f6a4a5043.png)

The engine does great once in the real-time 3D space, but these initial "screens" and "menus" just look bad for any of us with ultrawide setups.

**Comment by Necrym59** [comment]
My screens even worse than yours
![widescreen2](https://user-images.githubusercontent.com/95015657/161198383-b709524d-348e-4e0f-a298-c6b7a080e9f3.png)

**Comment by plemsoft** [comment]
@ArgentArts You can select Backdrop - Zoom,Center,Stretch , if you have it set with "zoom" then it looks like the zoom have a bug on widescreen monitors , is that the case ?

**Comment by Necrym59** [comment]
SETTINGS
![settings](https://user-images.githubusercontent.com/95015657/161231460-93791f32-8207-4fe5-ba2a-f278d80a9daa.jpg)
RESULT
![result](https://user-images.githubusercontent.com/95015657/161231498-414a7a3d-106a-4df5-8495-7595eb415f69.jpg)

**Comment by ArgentArts** [comment]
@plemsoft I think there's another bug here. I tried to create stand-alones with all three loading screen types (zoom, center, and stretch), but they all looked the same. When I went back into MAX, to the Storyboard Editor, and clicked on the Loading Screen, it was reset to Backdrop Zoom, even though I had selected one of the others.

**Comment by plemsoft** [comment]
@MonkeyFrogStudio Did i fix this ? think i was looking at it, is it fixed in the latest build , or do i remember wrong :)

**Comment by Necrym59** [comment]
Sorry Preben, its still the same regardless of which backdrop mode is chosen for me at least. In MAX Build 2022.04.29
Selected Centred
![selected](https://user-images.githubusercontent.com/95015657/166316182-dfe05134-dff8-47ee-b4de-07a18d6f4856.png)
Result ?? - Super Zoomed :)
![result](https://user-images.githubusercontent.com/95015657/166316251-cf7a69e4-26c8-4948-8306-e8b4d0511c7c.png)

**Comment by MonkeyFrogStudio** [comment]
@plemsoft Still the same for me, too. Latest experimental build.

**Comment by plemsoft** [comment]
@MonkeyFrogStudio @Necrym59 I think i found it :) but dont have a widescreen to test on, could one of you try this new .exe and let me know if it fix the zoom on widescreen:

https://drive.google.com/file/d/148Ab0XwRYkAoA3nGSvOgQ46msdn03VJg/view?usp=sharing

Thanks for your help :)

**Comment by plemsoft** [comment]
@Necrym59 Yes thats zoom working :) , cant you get "center" to work ? , just tried here it worked fine, how do you test it ?

**Comment by Necrym59** [comment]
Let me try it again

**Comment by Necrym59** [comment]
Ok tried again Selected Backdrop Centre, it shows ok in the selcetion screen
![Backdrop_Centre_select](https://user-images.githubusercontent.com/95015657/166435458-c52138a4-461f-4c16-b147-b11ccb784b6b.png)
Then either running test level mode or standalone game this is the result
![Backdrop_Centre_result](https://user-images.githubusercontent.com/95015657/166435555-5667dd09-3c9a-4053-9a72-bb02a72f2b0e.png)

**Comment by plemsoft** [comment]
@MonkeyFrogStudio @Necrym59 Thanks for your help, this has been fixed and will be in the next update :)

**Comment by Necrym59** [comment]
Great mate thanks.

**Comment by rvanner** [comment]
@MonkeyFrogStudio Can this be closed now?
