### ISSUE TITLE
GG Max - buggy asset rotation

### ISSUE THREAD

**Issue by Ghost-l0l** [TheGameCreators/GameGuruRepo#2855]
https://youtu.be/Pu6L2w1Bp3k - recorded on lastest build [experimental]

**Comment by ZakJudges** [comment]
Hi @Ghost-l0l, apologies for the late response on this. I have not been able to reproduce this issue using Aztec Column A, as shown in your video. It is possible that this bug is already fixed. Do you know if you continue to experience it in recent builds? Thanks :)

**Comment by AvengingEagle** [comment]
I am still experiencing very similar issues in the latest EXP build: https://youtu.be/hnk7erPQFsk

**Comment by LeeBamberTGC** [comment]
@Ghost-l0l Fixed for next EXP build by improving the AnglesFromMatrix function
