### ISSUE TITLE
GG Max - Bug - Storyboard - Invulnerable Single Level + Invulnerable Standalone

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#2904]
When testing the levels from the Storyboard, If you try to test a game using Invulnerable Single Level or Invulnerable Standalone, You still have Health, and you still die.

**Comment by plemsoft** [comment]
@Tum1370 Thanks for reporting this issue, this has been fixed and will be in the next update :)

**Comment by Tum1370** [comment]
@plemsoft 
Hi, I have just tested this on the latest experimental build that released just now today (3/5/22)
Both Invulnerable Single Level and Invulnerable Standalone from storyboard is still not working.

Maybe its not been added to latest EXP build today ?

**Comment by plemsoft** [comment]
@Tum1370 Should be in there , just tested again and it works fine here, it will still count down health until you reach 100 and it will never go below , give it another try :)

**Comment by Tum1370** [comment]
@plemsoft 
Hi, Just tested this again.
Yes it is working as you say, My HP will drop to 100 and never go below that.

When i first tested it, i just noticed the HP going down, where as when you test play from editor, you do not even have the HP showing on screen.

I will close this issue now.

Thanks
