### ISSUE TITLE
GG Max - Bug - Show Navigation Debug Visuals

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#2945]
If you test your game in the editor and use the Show Navigation Debug Visuals to check how the AI is working, After you kill and enemy with the Navigation mesh on, It will leave this White Box where the enemy dies, 
This white box is then impossible to remove / delete.

![image](https://user-images.githubusercontent.com/66874403/164942680-4939a271-6b74-475f-b18c-7dde9f430a68.png)

**Comment by plemsoft** [comment]
@Tum1370 Thanks for reporting this issue, this has been fixed and will be in the next update :)

**Comment by Tum1370** [comment]
@plemsoft 
After a quick test of this bug on the experimental version, The white box still appears as the enemy dies, But then it disappears as another one dies.
I did not see the white box on the editor after testing the game.
Ill close this one.

Thanks
