### ISSUE TITLE
locked doors and slidind doors

### ISSUE THREAD

**Issue by zeebon** [TheGameCreators/GameGuruRepo#3179]
cant seem to make locked doors open with a key or make sliding door work with switch looked at demo game switch escape and copied their setup still didnt work have had locked door and key working in the early version cant get it working know tried uninstalling it but the old stuff still there like saved games and old names still there

  regards mark

**Comment by Lemuripest93** [comment]
Old saves and maps are not found in the root installation folder, but in documents.

Follow the path of [> Your Computer > Documents > GameGuruApps > GameGuruMax > Files > mapbank] and you should be able to erase old saved maps/projects you no longer want.

Door behavior is weird for me right now as well, i'm sure the devs will have it sorted out in one of the future updates.

**Comment by zeebon** [comment]
Cheers for that

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by ZakJudges** [comment]
Hi @zeebon, would you be able to send a video of the issue, so we can see what's going on? Thanks :)

**Comment by zeebon** [comment]
It’s alright i got a runtime error and wiped everything out

Sent from my iPhone

On 23 May 2022, at 10:17, ZakJudges ***@***.***> wrote:

﻿

Hi @zeebon<https://github.com/zeebon>, would you be able to send a video of the issue, so we can see what's going on? Thanks :)

**Comment by Lemuripest93** [comment]
Here you go: https://youtu.be/aXuDuwcU5nw

**Comment by ZakJudges** [comment]
@LeeBamberTGC See Lemuripest93's comments about door behaviours: 

> Door Sliding - When "Open with E Key" is left unchecked, the key activates the door whether or not it's on the toggle or activate option (basically they function the same), when "Open with E Key" is left checked it still says the door is locked despite it not being locked. (the key is not necessary for the latter option like in the video, error on my part.)

I think this is mainly due to having too many settings/modes. Perhaps it should be split into two behaviors? We could have a sliding automatic door that can be locked/unlocked with a switch, and a sliding manual door that is opened by pressing E and can be locked/unlocked with a key/switch, just like a regular door.


> (Regular) Door - Key respawns when locked door is opened

I've looked into this one and I think its caused by `PerformLogicConnections()` 'undoing' a call to `Destroy()`. This would explain a few of the previously reported visual logic bugs. Any chance you could take a look at this to verify that is the case? Maybe I have been staring at it too long, could do with a second opinion. Thanks :)

**Comment by zeebon** [comment]
Thanks for that works a treat

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by LeeBamberTGC** [comment]
@ZakJudges Can you confirm the state of this issue, and resolve if quick to do :)

**Comment by ZakJudges** [comment]
Hi all, apologies for the late response! This should now be fixed in the latest build :)

**Comment by Lemuripest93** [comment]
The reappearing key bug has been fixed, but picking up a key will still open up a locked sliding door from far away.

**Comment by LeeBamberTGC** [comment]
@Lemuripest93 Should be fixed with the latest Behaviour scripts, check the next EXP build for confirmation.

**Comment by Lemuripest93** [comment]
Hey @LeeBamberTGC the bug seems to still occur, heres a video showing me recreating it right now by making a fresh level: https://www.youtube.com/watch?v=CYRSLuUA0Q8

I'll also include the level i made in the video if you want to test it yourself:
[SlidingDoorAndKeyTest.zip](https://github.com/TheGameCreators/GameGuruRepo/files/12601845/SlidingDoorAndKeyTest.zip)

I'm guessing this isn't that big a deal since most people probably wont try to use a key on a sliding door anyways, unless maybe they use the key on another device that opens the sliding door? but might be nice to have it looked over one more time anyway.

**Comment by LeeBamberTGC** [comment]
@Lemuripest93 This is great, was able to reproduce. I have forwarded it to Necrym :)

**Comment by Necrym59** [comment]
Sliding door has been fixed however as this particular door has some special options in its use as to how it operates the key will open the door only in auto-mode and only if door is locked.

**Comment by LeeBamberTGC** [comment]
@zeebon All three door behaviours now tested with key using logic link and with USEKEY field in Developer Settings, so you can lock them and use a key to open in next EXP build :)
