### ISSUE TITLE
Detection of bugs Issues 273 and 206 (Transparent texture of characters)

### ISSUE THREAD

**Issue by Shahin3d** [TheGameCreators/GameGuruRepo#330]
Hi
I've tested a lot
And I think I found the problem: #206&273

*Texture enemy characters: After testing a few times or Die - Transparent mode is found #273
*Zombie character texture #206

When you add decals folder items like smoke or fire to the scene:
This happens: After dying one or more times=the texture mode of the characters becomes Transparent!

Before adding items Decals:
![d-1](https://user-images.githubusercontent.com/36647058/43360009-04b75a40-92c3-11e8-9708-e435f2d43ee0.jpg)

After adding items Decals.
The problem now arises:
![d-2](https://user-images.githubusercontent.com/36647058/43360025-45eb54d0-92c3-11e8-9fac-e6e2283fa562.jpg)

I think this is because of a problem in decal_animate4.fx.
Previously this happened for (Issues 206, 273).
Please test it yourself.
I attached the fpm files.
Please fix this problem as soon as possible.
Thanks
[FPM-FILE.zip](https://github.com/TheGameCreators/GameGuruRepo/files/2238256/FPM-FILE.zip)

**Comment by Pirate-Myke** [comment]
I see the same thing with his map file after one death of the TPV player.

**Comment by demented-mind** [comment]
I can also verify this using Shahin3d's fpm file. See link below for videos of what is happening. 

https://forum.game-guru.com/thread/219900?page=2#msg2603797

**Comment by Shahin3d** [comment]
Hi - I tested it again - this problem still exists

![test](https://user-images.githubusercontent.com/36647058/45927773-0f96f480-bf45-11e8-9b02-c704ded822a1.png)

1- Create a third person character
2. Test the game
3- Die by enemy characters
4. Click ESC and exit test
5. Test the game again - you will probably see the problem.

**Comment by bonesy23438** [comment]
yeah same here theres a problem with the decal shader as i get the same problem when i add decals
![desktop screenshot 2019 02 04 - 13 53 20 100](https://user-images.githubusercontent.com/37757086/53204446-884cca80-3623-11e9-92d7-17d07d86825a.png)

**Comment by plemsoft** [comment]
@Shahin3d Thanks for reporting this,

This has been fixed and are ready for the next release :)

**Comment by LeeBamberTGC** [comment]
Can you provide a small FPM using stock media and a step by step that shows this transparency error in either first or third person perspective?  I have just received a report that this issue is still present in the latest beta build for first person perspective, thanks.

**Comment by plemsoft** [comment]
@LeeBamberTGC This was fixed for 3RD here.

The first person problem was reported here:
https://github.com/TheGameCreators/GameGuruRepo/issues/206

And Pirate-Myke confirmed that was also fixed.

Where was this reported ?

**Comment by LeeBamberTGC** [comment]
I got an email showing the issue in the shot posted by bonesy23438, as the latest beta build apparently still showed the issue. A fresh FPM showing it would confirm if the latest beta build fixes it.

**Comment by plemsoft** [comment]
@LeeBamberTGC Ahh yes i did not yet commit that fix , but it is fixed, i will make a new pull today so he can test it :)

**Comment by Shahin3d7** [comment]
Hello
I tested with version 2019.03.25.(publicpreview in steam)
[FPM-FILE.zip](https://github.com/TheGameCreators/GameGuruRepo/files/3310945/FPM-FILE.zip)

That's the problem.

![Untitled](https://user-images.githubusercontent.com/43903231/59858597-8526d880-9390-11e9-9421-cedd71670d22.png)

**Comment by LeeBamberTGC** [comment]
This will be fixed in the next beta build :)

**Comment by Shahin3d** [comment]
Thank you
fixthis issue.
