### ISSUE TITLE
Gameguru max runtime error 7018

### ISSUE THREAD

**Issue by 555cre** [TheGameCreators/GameGuruRepo#3561]
I bumped into this issue

**Comment by DaveTGC2** [comment]
Hi, are you able to give any more information? What where you doing at the time?

**Comment by synchromesh62** [comment]
I have seen this one fixed by verifying Max.
Give that a try.

**Comment by davetgc** [comment]
Is this fixed for you?

**Comment by 555cre8** [comment]
i recently imported new entities into my gameguru max through the import program, but then messed up yet they still showed up in gameguru max user area, can not delete old imports, every time I click on user that message comes up.  only when i click on user, and also my particles when looking at them on my screen do not show up in viewing area, it like the whole thing might have become corrupt?
