### ISSUE TITLE
FPS loss when level starts, only gets back to normal if I do certain actions.

### ISSUE THREAD

**Issue by waterdrinkingfox** [TheGameCreators/GameGuruRepo#3671]
Hello. I found this issue where when a level just starts, I have very low FPS until I do one of these things; Fire a weapon, jump (or go downhill/uphill) or pick up an item (edit: pressing "0" or getting spotted by an enemy will make the FPS go back to normal too). However crouching or scoping with a weapon did not do anything. I experienced this in a test game I made, but also on the demo game Indian Strike Force. I have no FPS loss when I playtest the game in the editor though.
Specs: RTX 3060 Laptop, 16GB of RAM, Ryzen 5 5600h
Video:

https://user-images.githubusercontent.com/112423658/188296008-0eec70f3-4ec7-4b10-be67-1b5cd05846af.mp4

**Comment by MonkeyFrogStudio** [comment]
This had been reported here:

https://github.com/TheGameCreators/GameGuruRepo/issues/2300

And was fixed at one time, but appears to be back. Perhaps there are some clues in that thread that can help you resolve it while TGC looks into it.

From that other thread, it appears (or at least was the case then) that the issue is due to some extra files being saved with the stand-alone that aren't needed. For some reason, MAX gets hung on one of them (or more) until you start to move, etc. I had found that deleting all the unneeded files solved the stutter.

**Comment by waterdrinkingfox** [comment]
Oh so this seems to be an already known bug. I see that when you walk in-game, the stuttering stops, which is not the case for me. I tried removing the folder you removed but I still have the problem, but instead of initially running at around 10 FPS, it runs at around 25 FPS. (I normally have 65+ FPS). I'll let the guys at TGC try to solve the issue as I don't have the technical knowledge for all of this.
