### ISSUE TITLE
GameGuru MAX - Request - A "Refresh" Button

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#3742]
MAX has a way of "holding" on to things. For example, if you use the importer to import a model you already have (maybe you've updated the model), MAX asks if you want to replace it. After you agree and move on, the model is replaced in the file system, but MAX is not updated in the viewport or test game. You have to exit out of MAX and restart before the new model will replace the old one that was originally in your scene. 

Another example is when you update a script/Behavior. You seem to have to disassociate the old Behavior with the object, save, exit MAX, restart, and then attach the new. And even then you may need to save, exit, and restart to make sure there are no remnants of the old script in effect.

In cases like this (and others), wouldn't it be nice if we could just hit a "Refresh" button that would cause MAX to look for any changes and apply them, completely clearing out the old, replacing them with the new? It would be much faster than saving the level, exiting MAX, restarting MAX, clicking on the level you want, clicking again to get from the Storyboard and into the actual level, resetting all your settings (like grid settings and accessing advanced features that keep resetting), then finally hoping that the new changes actually took place so you don't have to do it all over again ... and having to do this each time you update something, like a model or a script.

When testing a new Behavior, we can sometimes go through several iterations as bugs are found and squashed and as things are tweaked or new features added. It's a bit of a PITA to have to restart MAX every time, resetting all your settings, just to test a script (for example). 

Instead of that, a single button that's pressed that will refresh all models, all scripts, etc., clearing the cache of all old stuff and making sure your level is completely up-to-date.

**Comment by davetgc** [comment]
I've been thinking for quite sometime that an update all button for scripts would be good. Say for example you wanted to update all beds of a single type to have a sleep script, you could just click UPDATE ALL.

**Comment by MonkeyFrogStudio** [comment]
@davetgc Certainly a good idea. As long as we can also update EVERYTHING, but scripts aren't the only thing that need to be updated in MAX (which currently require a restart of MAX to make them come into effect). As pointed out, making a change to a model (re-importing) needs a refresh, too. ;)

**Comment by synchromesh62** [comment]
That still may not work with Models though .. The problem i found is the old model settings are saved to the Map file and not just the .fpe file. So no matter what you refresh the map will load the old texture etc settings from the last .fpe it has saved within it.
I usually have to physically replace the model on the map then resave. Then just reload the Map.

**Comment by MonkeyFrogStudio** [comment]
@synchromesh62 That hasn't been my experience. For example, I had a model where I noticed there was a small error in the UV map. I went in to Blender, made the correction, exported, and reimported into MAX. After restarting MAX, the model displayed the correct UVs. So, it did update. 

In any case, if it didn't work, then that would also be something they would have to work on, right? In other words, if a "refresh" button would not be enough to do the trick, then TGC would have to find a way to make it work, because it should. We should be able to update our models without having to restart the editor, after all.

**Comment by synchromesh62** [comment]
@MonkeyFrogStudio 
Perhaps its because my main model is using Multiple materials.
When i make adjustments or add new the texture then re - import the layout in the new .fpe changes so when i load the map with the new model the textures are all in the wrong place. However, the new model dragged in is just fine.

It could just be the software i use just reorganises them on export. But it does bring to light that settings are saved to the Map file.

**Comment by MonkeyFrogStudio** [comment]
@synchromesh62 Yes, settings are saved to the map file. There has to be a way to differentiate the object used in the level from the one in the Object Library sitting there ready to be used. For the one in the level, the end-user could change any number of things - the collision shape, adjust material settings, etc. So, this is necessary. Regardless, the software needs to recognize when things change and see if something needs to be done about it. 

For example, if I bring a model into the scene and don't change anything about it (the collision shapes is not change, material settings are at the default, etc.) and, later, I update that model (i.e. I reimport the model), then MAX should know to automatically update all instances of that model, even in the scene.

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio Thanks for the feature request, and hits on a critical feature if MAX is to be used for 'proper' game development :)  My idea is to take it just one step further, and often used in other professional toolchains, which is live updating.  That is, as soon as a file registers a change, a background task in the game engine instantly updates the asset/resource associated with that file, even if that asset is being used during a test game. In this way, tools can be open in parallel to game development, used as needed, the asset saved, and you don't then need restart/reload/replay/reXXX to see your change in situ, it's just there (as though the change was always there in the first place). I know we are not aiming to embarass Unity or Unreal, or any professional tool for that matter, but isn't easy game-making about making the production of your game easier and quicker :)  Bottom line, no need for a specific REFRESH button if the engine KNOWS when to update.  Tackl;ing scripts might be a nice place to start, however.

**Comment by MonkeyFrogStudio** [comment]
@LeeBamberTGC That would be totally awesome, to be frank. I had just re-imported a model today (made corrections to it). MAX faithfully asked if I would like to replace the model. I said yes. But I had to restart MAX to see the changes to the model in my level. Live updating would definitely solve these sorts of issues. Thanks! :)

**Comment by DaveTGC2** [comment]
As more and more artists are working on content, I think the idea of adding a refresh button is becoming far more relevant.

**Comment by davetgc** [comment]
@ZakJudges - I've pushed this up as a feature request as the need to restart MAX to see your imports is hitting artist development time.

**Comment by OldFlak** [comment]
Yes, have seen all issues mentioned in OP. Tis very cumbersome - especially when developing scrips.
Still seeing the models not updating properly in current EXP unless you close and reload MAX.

With scripts I was wondering if MAX can perhaps just read the script directly from file in test-game on every load - and only bind them to the level when creating standalone?

**Comment by MonkeyFrogStudio** [comment]
It appears that models are instantly updating if you import a newer version, so I am closing this one.
