### ISSUE TITLE
Terrain glicthing when using Building Editor

### ISSUE THREAD

**Issue by extremestrategy** [TheGameCreators/GameGuruRepo#3929]
When using the building editor the terrain will glitch resulting in either infinite holes or in towers so high they go out of sight.

![Screenshot 2022-12-04 170806](https://user-images.githubusercontent.com/114613272/205518255-61611487-2d91-4f54-8d9e-600b888a07d0.png)
![Screenshot 2022-12-04 170726](https://user-images.githubusercontent.com/114613272/205518258-700acaa2-777e-4d91-bcf3-a4283ad5025f.png)

**Comment by ZakJudges** [comment]
Hi @extremestrategy, thank you for reporting this issue. I have added some changes which should fix this for you. I will post here when a new experimental build is available to download for you to confirm the fix. Thanks :)

**Comment by extremestrategy** [comment]
I tried the EXP build 2022.12.14 and it still happened.
![image](https://user-images.githubusercontent.com/114613272/206282565-d6ac1ba3-167a-40e2-a479-9c3f9e487dfc.png)

**Comment by ZakJudges** [comment]
@extremestrategy Would you be able to send me the map file, and the exported building files? That will allow me to hopefully reproduce the issue. My email address is zak@thegamecreators.com

The map will be in your documents -> mapbank folder. The building files will be in entitybank\user

Thanks :)

**Comment by extremestrategy** [comment]
Sent.

**Comment by ZakJudges** [comment]
@extremestrategy Thank you for sending over the files.

I loaded the map in the latest experimental build, but wasn't able to reproduce the issue:
![Screenshot 2022-12-08 091139](https://user-images.githubusercontent.com/32545391/206406005-c710f3eb-3f2a-4b6a-8577-b26e83a94de2.png)

In your Steam library, does GameGuru Max has the experimental tag? Like so:
![Screenshot 2022-12-08 091121](https://user-images.githubusercontent.com/32545391/206406099-89a75882-ee42-4c9b-9c98-4971b700d7c6.png)

**Comment by extremestrategy** [comment]
No it does not.
![image](https://user-images.githubusercontent.com/114613272/206485882-fb4b4dc3-8796-4795-9676-b61236534c25.png)

**Comment by ZakJudges** [comment]
@extremestrategy You can find instructions for switching to the experimental build here: https://github.com/TheGameCreators/GameGuruRepo/issues/3907

**Comment by extremestrategy** [comment]
I tested it in the experimental build and it works now, thank you.
