### ISSUE TITLE
Characters shine in standalone (Notebook)

### ISSUE THREAD

**Issue by sfkylcnky** [TheGameCreators/GameGuruRepo#398]
In a standalone when we start the game at our test notebooks shown characters are shining at High and Medium graphic settings but they don't shine at Low settings. If we open the same standalone game from our desktop shining is not observed neither at High nor at Medium graphic settings. So shining does not occur at desktop but it occurs at notebooks when Medium or High graphic settings selected. The configurations of the computers are listed below

Desktop:
AMDFX4130 3,80 ghz cpu + 16 gb ram + NVIDIA GeForce GTX1050 + Latest Driver Version 411.70 + Windows 10 Pro 64 bit

Notebooks:
i7 7700hq 2,80 ghz cpu + 16 gb ram + NVIDIA GeForce GTX1050 + Latest Driver Version 411.70 + Windows 10 Pro 64 bit

i7 4700hq 2,40 ghz cpu + 16 gb ram + NVIDIA GeForce GTX850m + Latest Driver Version 411.70 + Windows 10 Pro 64 bit

Desktop High
![01](https://user-images.githubusercontent.com/37545408/46156236-b2bb7700-c281-11e8-9340-8abdf3ad6a22.jpg)

Notebook High
![02](https://user-images.githubusercontent.com/37545408/46156244-b818c180-c281-11e8-8439-e4befaf70e8f.jpg)

Notebook Low
![03](https://user-images.githubusercontent.com/37545408/46156247-bb13b200-c281-11e8-9c30-5eecc5522ce2.jpg)

**Comment by LeeBamberTGC** [comment]
Not able to reproduce with latest build, and suspect this was related to another issue which has been fixed. Will be closing at end of June unless it can be reproduced with latest beta build.

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
@plemsoft 
Duplicate and another is on the Bug list which seems to be linked to AMD cards only ..

**Comment by sfkylcnky** [comment]
Not resolved. Not only linked to AMD cards only as I am using Nvidia as stated

**Comment by LeeBamberTGC** [comment]
See "https://github.com/TheGameCreators/GameGuruRepo/issues/676#issuecomment-610449011" for bug duplication.

**Comment by LeeBamberTGC** [comment]
Could you attach one of the character creator FPE files of a character that glows, thanks!

**Comment by sfkylcnky** [comment]
Fantasy Pack\Characters\Skeleton.fpe

[Skeleton.zip](https://github.com/TheGameCreators/GameGuruRepo/files/4461070/Skeleton.zip)

Scifi Pack\Characters\Spaceman.fpe

[Spaceman.zip](https://github.com/TheGameCreators/GameGuruRepo/files/4461073/Spaceman.zip)

**Comment by LeeBamberTGC** [comment]
Character Creator characters now use the PBR shaders so hopefully no more glow.
