### ISSUE TITLE
GG Max - Experimental Build - VR and Standalone Test All Levels

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#4043]
Hi,
When you have the experimental VR support enabled,
and you then try to TEST ALL LEVELS from the Storyboard, and you have the box ticked to "STANDALONE TEST ALL LEVELS"
Then you click the TEST STANDALONE button in storyboard, The game launches in to VR mode, and not just Desktop mode.

Not a major problem as its easy to just disable the VR Support in settings, and it works fine then.

**Comment by LeeBamberTGC** [comment]
@Tum1370 Some of the labels have changed since this report, and following the steps I see the standalone is running in desktop mode rather than VR mode so I am assuming we fixed this at some point in the last year:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/9b161395-6b3a-478c-8bd2-564c2552becc)

**Comment by Tum1370** [comment]
@LeeBamberTGC I have just tested this bug.
I can confirm that this bug is still in the latest EXP build of Max.

I always have the option for VR in the setting enabled.
And when i try to TEST ALL LEVELS from the storyboard, with VR enabled, i can still confirm, the GUN is not visible on the player.

**Comment by LeeBamberTGC** [comment]
@Tum1370 Is the bug report that "The game launches in to VR mode, and not just Desktop mode." or "the GUN is not visible on the player?. The weapon visibility issue is reported in another post :)

**Comment by Tum1370** [comment]
@LeeBamberTGC I am not sure, i have not tested it in VR. All i have done is TEST ALL LEVELS while the VR option is enabled in settings, and on my desktop the gun is not visible.

I will post here again after i have had time to test whether it actually launches in to VR mode when you Test All Levels.
