### ISSUE TITLE
Character Creator In lastest PP 2016.09.23 can not see bottom row of bodies 

### ISSUE THREAD

**Issue by Ratall** [TheGameCreators/GameGuruRepo#410]
Basically when you go to select a body you scroll row and you can not see the last row of thumb nails.
![can not see bottom row in bodies](https://user-images.githubusercontent.com/35710601/46384690-f5a2a200-c6fa-11e8-9e1d-605ca900b99c.PNG)

Notice the scroll bar is at the bottom and the last line of thumbnails is barely visible.
[https://forum.game-guru.com/thread/220095](url)

**Comment by plemsoft** [comment]
@Ratall Thanks for reporting this,

Just tested this in the latest version ,and it seams to work fine now , could you confirm that this is fixed in the latest version , thanks :)

**Comment by Ratall** [comment]
@plemsoft 

I only have access to the public preview (2019.03.25 - March Fixer) and the problem still exists in that version.
Sorry :(

**Comment by synchromesh62** [comment]
Just tested for you in the latest Beta 28B 
Still not able to scroll down to the bottom row

**Comment by plemsoft** [comment]
@synchromesh62 Ahh thanks , we cant see this in the Repo version , this only happens when you install additional assets to the "Character Creator" , anyway found and fixed it , ready from the next release :)

**Comment by Ratall** [comment]
Can confirm appears now fixed thankyou
