### ISSUE TITLE
Game Guru Crashes and or black screens in experimantal build-AMD RX 6600 XT Bug

### ISSUE THREAD

**Issue by A3DArtist2023** [TheGameCreators/GameGuruRepo#4124]
Okay So I loaded Experimental Build- Have Black screen in Editor, and or game play, Can't load terrain-black screen or play game-black screen. I can load last known preview build works fine can see the editor window fine, but after building the level with simple objects and running the game it with freeze and crash. Okay So i did a test and uninstalled the adrenaline Software i can run the software with no problems after that, as soon as i re install the adrenaline software version 22.11.2  it goes back to black screen, Why?? is that? AMD RX 6600 XT. Talked to lee about it told me to run exp version still having issues. Classic runs fine no problems??

**Comment by davetgc** [comment]
Thanks for the report. Other users are reporting that the AMD bug is fixed. Does anyone else have a  AMD RX 6600 XT they can test this issue with please?

@A3DArtist2023 - Have you checked your drivers, and tried either the latest or rolling the drivers back?

**Comment by SteveSfara** [comment]
I own a RX6600. I tried updating the drivers, uninstalling the Adrenaline Software, I still have the black screen.

**Comment by synchromesh62** [comment]
@davetgc 
It does appear the 6600 does have its own issue **unrelated** to the AMD driver timeout issue all AMD users suffered in the DX12 build. This particular card has been mentioned many times on the forums.

**Comment by A3DArtist2023** [comment]
Okay So I rolled back my Drivers to Adrenalin 22.5.1 (WHQL) there must be a problem with the drivers in Adrenalin 11.22.2 (WHQL) the newest driver. So I am running good so far with the older driver.!!

**Comment by SteveSfara** [comment]
@A3DArtist2023 I just did the same. GameGuru MAX still has the black screen.

**Comment by davetgc** [comment]
There's certainly a mixed bag of results here. Thanks for the extra information. Please keep it coming if anyone can add more.

**Comment by A3DArtist2023** [comment]
@davetgc Yes so far so good haven't had any other issues after rolling back the Adrenalin driver to 22.5.1 I also can run it with out the driver installed too because i did try that as well. @SteveSfara Are you still getting a black screen in the experimental build even after uninstalling the Adrenalin driver completely??

**Comment by SteveSfara** [comment]
@A3DArtist2023 I have tried it again. Now it works, somehow.

**Comment by Frantic-bookworm** [comment]
6700 XT suffering with black screen have latest software version 22.11.2 adrenalin cant play edited games buiuld from scratch either issue is 3 weeks old want to wait for fix rather than roll back

**Comment by A3DArtist2023** [comment]
@Frantic-bookworm There is a work around for the AMD 6000 series cards and i ended going back to the current 22.11.2 driver and used the fix give it a try it worked for me. I had someone on discord point me in the right direction on the #VR-Chat under game guru max discord- take a look in their for the work around see if it will work for you as well. I had to add some files and no more black screen. do you have discord! here is the link. https://discord.com/channels/950796460683829329/1057991886964535376 follow this link.

**Comment by A3DArtist2023** [comment]
@SteveSfara There is a work around for the AMD 6000 series cards and i ended going back to the current 22.11.2 driver and used the fix give it a try it worked for me. I had someone on discord point me in the right direction on the #VR-Chat under game guru max discord- take a look in their for the work around see if it will work for you as well. I had to add some files and no more black screen. do you have discord! here is the link. https://discord.com/channels/950796460683829329/1057991886964535376 follow this link.

**Comment by A3DArtist2023** [comment]
This guy had a fix give him credit on discord #Max-VR-CHAT:
Istarias
 — 
02/05/2023 2:04 AM
For those who don't know, and since someone mentioned their problems recently in this chat (it's posted on the Steam discussions for GGMax) :

A Fix For AMD RX 6000 Series Owners
 
A simple fix for now is download DXVK (https://github.com/doitsujin/dxvk/releases/tag/v2.0)

1. download and extract the DXVK files
2. In the x64 folder, copy all 4 files
3. Go to where you installed GamuGuru MAX
4. Paste the 4 files where the "GameGuruMAX.exe" file is.
5. Do the same for the Building Editor & Particle Editor folders (It can be found in the "Tools" folder)
6. (If still having issues) Downgrade to a older version of Adrenaline (I downgraded to 22.5.2)... I don't know if this step is necessary, but i wanted to be safe.

This temporary fix will work until an official patch releases. 
GitHub
[Release Version 2.0 · doitsujin/dxvk](https://github.com/doitsujin/dxvk/releases/tag/v2.0)
Driver compatibility
A Vulkan 1.3 capable driver and wine version are required to run this version of DXVK. See the driver support page for details.
Many features in this release, especially the sh...

**Comment by A3DArtist2023** [comment]
This fix worked for me i am able to play and run all editors in GGMax- So far so good back to making 3d models for me hope mention above hels others in here to.
