### ISSUE TITLE
Menu\Hud pixel issue

### ISSUE THREAD

**Issue by michaeloldman** [TheGameCreators/GameGuruRepo#423]
So for some time now I have been aware of an issue with full-screen images leaving a 1 pixel gap along the bottom and right side of the screen. I have only tested this with 1920x1080 and 1366x768 screen sizes.

It may sound trivial - but it really detracts from the overall polish of a game.

It happens most noticeably on the Menu screens in a Stand-Alone-Build, but is also an issue in-game both in stand-alone and in test-game.

The really weird thing in the Menu screens, is you can draw a white line along the bottom and right side of the screen with the mouse.

It also is very noticeable if you have a different colour graphic for the 'Lost' screen which can be seen when going back to the Main screen.

Most of this can be worked around by having the same graphic for each page or using the similar colours of course, but the white mouse draw issue is always a problem no matter what image is used.

For clarity, the loading screens are not using the grow\shrink animation but just static.

Some pics to illustrate:
Note you will have to click the image so it loads in a new window to see the issue clearly :)

The main menu screen when first loading the game:
![main_firstload_scr](https://user-images.githubusercontent.com/12246318/46797789-da3f3300-cd9b-11e8-9736-750987686bf8.png)

Using the mouse to add artistic flare :)
![main_mousedraw_scr](https://user-images.githubusercontent.com/12246318/46797819-efb45d00-cd9b-11e8-89d3-b5271f68e142.png)

The LOST screen - Using a bright colour to illustrate this issue. This screen already has the 1 pixel issue when loaded after dying in game:
![fail_scr](https://user-images.githubusercontent.com/12246318/46797941-3f932400-cd9c-11e8-8001-f20d8f1ffbbf.png)

And of course going back to the main screen from the 'Lost' screen is very noticeable:
![main_after_fail_scr](https://user-images.githubusercontent.com/12246318/46798067-93057200-cd9c-11e8-957e-f2a4ee5c1611.png)

Thanks for reading.

Reliquia....

**Comment by plemsoft** [comment]
@michaeloldman Thanks for reporting this,

Yes there was a slight scale issue when using 100,100 percent sprites (your background).

This has been fixed and are ready from the next update :)

**Comment by michaeloldman** [comment]
Thank Preben :)
Has that been added yet? Just tried in 06 26 update and the issue is still there.

Reliquia....

**Comment by plemsoft** [comment]
@michaeloldman No not yet its in my local branch , i think i will sent a update tomorrow or so ... :)

**Comment by michaeloldman** [comment]
No probs, thanks Preben

Reliquia....
