### ISSUE TITLE
GameGuru MAX - Bug - Stand Alone

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#4280]
As a test, I saved a stand alone version of my Cyberpunk Streets DLC. None of the **Change Texture** materials had emissive, despite them having emissive in the test game.

**Comment by plemsoft** [comment]
@MonkeyFrogStudio Thanks for reporting this issue, could you e-mail me a level with one object that have this problem, so im able to test e-mail: plemsoft@gmail.com
Thanks :)

**Comment by MonkeyFrogStudio** [comment]
@plemsoft I've sent you an email with a question. Please let me know if you've received it. Thanks. :)

**Comment by MonkeyFrogStudio** [comment]
@plemsoft I looked in the stand alone folder created for the test and can see the issue. MAX did not copy over the emissive texture, only the _color and _surface.

**Comment by plemsoft** [comment]
@MonkeyFrogStudio This has been fixed and will be in the next EXP update , perhaps it dont make it into todays update but then in the next :)

**Comment by MonkeyFrogStudio** [comment]
@plemsoft Apparently this has not yet made it into one of the builds as this is still not working on my end. Thanks. :)

**Comment by MonkeyFrogStudio** [comment]
@plemsoft I can confirm this has been fixed and is in the latest experimental build. I will close this now. Thanks for fixing this!
