### ISSUE TITLE
GGMAX Bug (EXP Build) - Hotkeys Bar icons don't appear in the second level

### ISSUE THREAD

**Issue by LukeTheLukeLTL** [TheGameCreators/GameGuruRepo#4347]
As you can see from the photos the icons can be seen in the first level, but in the second level they disappear. Even if the icons are not there I still can use the weapons. I have the same problem in the standalone and while trying the game in GGMAX.

First level:
![BugGGMAX_1](https://user-images.githubusercontent.com/103126963/228666641-4b7afd93-1589-41dc-8307-ebca47366f16.png)

Second level:
![BugGGMAX_2](https://user-images.githubusercontent.com/103126963/228666651-f825154b-e2be-4529-8e41-b589ba39ce30.png)

**Comment by plemsoft** [comment]
@LukeTheLukeLTL Thanks for reporting this issue , i was not able to reproduce it , but we did make many changes to standalone the last few days , so perhaps its already fixed in my version , could you try again when you get the next EXP update and let me know if this is also fixed for you, you need to generate a new standalone when you get the update , Thanks for your help :)

**Comment by LukeTheLukeLTL** [comment]
> @LukeTheLukeLTL Thanks for reporting this issue , i was not able to reproduce it , but we did make many changes to standalone the last few days , so perhaps its already fixed in my version , could you try again when you get the next EXP update and let me know if this is also fixed for you, you need to generate a new standalone when you get the update , Thanks for your help :)

I tried to create a standalone with the new build but the issue is still present.

**Comment by LukeTheLukeLTL** [comment]
Some icons appeared after the last update. The knife one and the AK one are still missing.
![HUDWIP](https://user-images.githubusercontent.com/103126963/229244970-f193ce2a-003d-43ef-95b0-3b0a859d098e.png)

**Comment by LeeBamberTGC** [comment]
@LukeTheLukeLTL This will be fixed in the next EXP build

**Comment by LeeBamberTGC** [comment]
@LukeTheLukeLTL did you try a fresh game project creation?  And using the latest EXP build?  Can you confirm that they show up in Test Level, and if so, it sounds like the project files are not being copied over when making a standalone.

**Comment by LukeTheLukeLTL** [comment]
> @LukeTheLukeLTL did you try a fresh game project creation? And using the latest EXP build? Can you confirm that they show up in Test Level, and if so, it sounds like the project files are not being copied over when making a standalone.

I tried creating a new project and doing the standalone and it works there, so it's an issue with this project. I tried to see if I had set something wrong in the collectables list but everything seems to be set right.

**Comment by LukeTheLukeLTL** [comment]
I solved the issue, but to do so I had to delete the "Collection - items" list and I had to put the AK and knife in the second level as well to make the icons appear. I'm closing the issue now, since it has been solved. Thanks for the fix :)
