### ISSUE TITLE
Scaled partiles can't be selected

### ISSUE THREAD

**Issue by TenebreGaming** [TheGameCreators/GameGuruRepo#4668]
(Build 2023.05.25) This bug is very easy to reproduce.

1) Drop a default particle into your level (I initially discovered this with thick smoke, but it works with all)
2) Set the scale of the particle to 0 or crank it up to max (it doesn't need to be at max, but it reproduces every time)
You can no longer select the particle

At lower scale factors (like around 8k-10k range) you can sometimes select the particle from certain angles, but at 0 or large values it cannot be selected at all.

I noticed this because a particle I had placed doesn't appear to be working for some reason and I can't select it to figure out why.

**Comment by LeeBamberTGC** [comment]
@TenebreGaming I added 3 particles of smoke and was able to scale each one and then move them about, selecting between them. This may have been fixed since the report:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/dc9034fd-5e8c-4f45-9adc-4c399c94b620)

**Comment by imothep85** [comment]
the problem is still present, i scaled the particle to the max and then it become impossible to move the emitter in my level i use the latest version of ggmax experimental.

**Comment by wizardofid29** [comment]
This issue hasn't been fixed as yet can confirm scaled particles can't be selected...

**Comment by LeeBamberTGC** [comment]
@TenebreGaming Turns out the special code that prevents a building being accidentally clicked when inside it also applied to markers such as the particle marker, so when it was scaled up, you ended up kind of inside it, and so no selection. Fixed for the next EXP build :)

**Comment by TenebreGaming** [comment]
This does appear to have been fixed.
