### ISSUE TITLE
Player Marker defaulted to Melee. 

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#4817]
The Player Marker defaulted to Melee is so frustrating. 
When im testing my stuff or others i have to remove those hands every time i place a marker which is constant if you are testing areas in your levels. Please reset it to **Non** as it was

**Comment by DBird-1994** [comment]
Yes, If I have to see that knuckle-cracking animation one more time I'm gonna burn this place to the ground.   I would also prefer it default to "No Weapon"

**Comment by extremestrategy** [comment]
Agreed, this is extremely annoying.

**Comment by Blood-Moon-Interactive** [comment]
I don't know what these guys are talking about. I find the sound soothing. Keep it!

**Comment by synchromesh62** [comment]
The Samaritans just called **ME** 
Thats how bad it is :)

**Comment by OldFlak** [comment]
Couldn't agree more - would also like to see **No Weapon** as default.
+ 💯

**Comment by MonkeyFrogStudio** [comment]
I agree. Melee should not be the default. I much prefer testing with nothing showing and turning on melee or weapons as needed.

**Comment by Kitakazi** [comment]
Yes, this is a horribly annoying bug. Like having a hang nail or something.

**Comment by synchromesh62** [comment]
Looks like this is fixed .. Yay !!
Can anyone else confirm before i close it pls :)

**Comment by MonkeyFrogStudio** [comment]
@synchromesh62 I just opened MAX, it didn't update even though I'm on experimental. So far, the melee hands still show up by default on my end.

**Comment by Kitakazi** [comment]
Same as MonkeyFrog for me. Steam has no update.

**Comment by synchromesh62** [comment]
Really weird ... tried everything and cannot get it now .. 
i will remove my comment obviously still an issue

**Comment by OldFlak** [comment]
Not seeing it here now when placing new player marker down

But sometimes I get this

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/12246318/dfd7a01c-369a-48b2-9cc8-5e6de3cd92ad)

**Comment by LeeBamberTGC** [comment]
@synchromesh62 Fixed for next EXP build.

**Comment by synchromesh62** [comment]
Confirmed here .. 
Thanks Lee thats awesome :)
