### ISSUE TITLE
Weapons attacking randomly

### ISSUE THREAD

**Issue by extremestrategy** [TheGameCreators/GameGuruRepo#4935]
When using certain weapons they will make an attacking animation when the player is walking/running, these weapons include the Max/Colt, the Aztec Axe, the Aztec Spear, and the Railspikespear, when this glitch occurs it is only an animation and sound, and there is no damage being dealt to any enemies that the movements are directed at.

In the video below you will see the ammo stays the same as it is purely animation and sound, also in the entire video I did not right click, or left click once, the only mouse controls were directional.

https://github.com/TheGameCreators/GameGuruRepo/assets/114613272/6ba54bac-f42d-4909-9fdd-65788be898d2

Edit:  This bug only appears when the player spawns with the weapon already equipped, if it is picked up, bought, taken from an opponent, or gotten during the level in any way it doesn't seem to glitch out, the aztec spear will yank to the side randomly when the player moves but will not do an attack animation.

**Comment by LeeBamberTGC** [comment]
@extremestrategy This code is still in high flux so it may already have been fixed this one.  When equipping and running with the Max\Colt on my latest EXP build the gun is straight:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/3e0a636e-6521-401e-8a35-9b37252722c1)

**Comment by extremestrategy** [comment]
I'm still having the bug, was it equipped or did you spawn with it equipped?  Because you have to spawn with the weapon already equipped otherwise it doesn't act up.

**Comment by extremestrategy** [comment]
Well it's been a few weeks, and it's still happening, would the weapons I brought in from Classic be effecting the Max stuff?

**Comment by LeeBamberTGC** [comment]
@extremestrategy Not seen this one for a while now, and have since updated the model animations since seeing this too. First, we will need to ensure you are on the latest EXP Build and do not have old model files floating about. My own simple test looked fine:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/6a8e5ef1-48d3-4dd8-997d-7b2766798397)

I have attached the simple level with just the COLT in there, let me know if it displays weird animations, thanks.
[MAXCOLTONSTARTMARKER.zip](https://github.com/TheGameCreators/GameGuruRepo/files/12915935/MAXCOLTONSTARTMARKER.zip)

**Comment by extremestrategy** [comment]
Thanks @LeeBamberTGC , it's still bugging out and doing the animations thing, it could be an overlap of files and if it is I don't know how to fix it, even in your world you sent me it's still doing it, and I'm not sure why all the weapons were in the side tab, I scrolled over them all so you could see they were there, even though I didn't add any of them, as for the EXP build, I just keep updating as the EXP builds role out, but I don't know where to find which exact EXP build I am on.

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/114613272/9447915f-a45c-42f1-9d9b-02b5080d8db0)


https://github.com/TheGameCreators/GameGuruRepo/assets/114613272/d3dcca96-1a81-49d6-856d-4f2e7697bfb5

**Comment by extremestrategy** [comment]
@LeeBamberTGC I did what you suggested, and now the weapons work, how do I get the messed up files out of the old folder and then replace it as new?

**Comment by LeeBamberTGC** [comment]
Delete the gamecore/guns/max folder in the old writables area
