### ISSUE TITLE
The Black Window in the 'Editor' mode on the last update on Steam version in the drive version 23.9.3 on the AMD Radeon 5500XT (4GB)

### ISSUE THREAD

**Issue by Mishahhi** [TheGameCreators/GameGuruRepo#4988]
Please note, that the Black Window in the 'Editor' mode on the last update on Steam version in the drive version 23.9.3 on the AMD Radeon 5500XT (4GB)

Link on the problem: https://youtu.be/ZF0YKrKzBYY

**Comment by Mishahhi** [comment]
@davetgc I am ready to help with this bug. Just tell me what needs to be done.

**Comment by davetgc** [comment]
@Mishahhi - I've assigned this to our lead developer. If he needs any more information, he'll be in touch.

**Comment by LeeBamberTGC** [comment]
@Mishahhi Can you send a screenshot of your MAX root folder, here is mine with the extra files showing that my AMD fix is in operation:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/09061139-87e7-4a6d-8524-5084dba61c55)

**Comment by Mishahhi** [comment]
> @Mishahhi Can you send a screenshot of your MAX root folder, here is mine with the extra files showing that my AMD fix is in operation: ![image](https://user-images.githubusercontent.com/35840583/273274016-09061139-87e7-4a6d-8524-5084dba61c55.png)

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/20231122/85670ae4-5927-400d-8a50-eced4a4ef28b)

**Comment by LeeBamberTGC** [comment]
@Mishahhi Thanks for the quick reply, I really meant the actual list of files in this folder, I want to confirm you have them all and are using the AMD workaround (it replaces DX11 calls with Vulkan ones)

**Comment by Mishahhi** [comment]
@LeeBamberTGC The problem has been solved. Thanks! However, another one has appeared, but I will write about it in more detail later if I can't cope. I want to get to know the problem personally and solve it myself.

**Comment by LeeBamberTGC** [comment]
@Mishahhi Always the best way :)  Best oif luck, thanks for the report!!

**Comment by bulut-dev** [comment]
> @Mishahhi Thanks for the quick reply, I really meant the actual list of files in this folder, I want to confirm you have them all and are using the AMD workaround (it replaces DX11 calls with Vulkan ones)

I have the same problem and still not fixed . What does this mean =  (it replaces DX11 calls with Vulkan ones) ?

**Comment by LeeBamberTGC** [comment]
@bulut-dev It simply means that some AMD cards / drivers have some issues with DX11 based engines, and can cause the black screen in the editor. Our workaround was an abstraction layer that recasts DX11 calls to Vulkcan calls and uses the Vulkcan support on those AMD cards to get MAX up and running. Not a perfect solution until MAX moves to DX12.

**Comment by bulut-dev** [comment]
will there be an update for this problem?

**Comment by LeeBamberTGC** [comment]
Mishahhi's issue has been resolved. @bulut-dev Can you send a screenshot of your MAX root folder like @Mishahhi did above, thanks!

**Comment by bulut-dev** [comment]
![2023-10-12 20_51_55-Window](https://github.com/TheGameCreators/GameGuruRepo/assets/76091156/3d08a1d7-dc5e-4aa8-9f3a-3f1e8b717155)

**Comment by LeeBamberTGC** [comment]
@bulut-dev The files look good, and also the AMD fix seems to be there too.  Can you make a short video showing launching MAX from the Steam client and showing the black window issue, thanks!

**Comment by bulut-dev** [comment]
https://github.com/TheGameCreators/GameGuruRepo/assets/76091156/b1cc3f54-4578-47b0-9b4f-14822586cea8

**Comment by bulut-dev** [comment]
the screen recording application also stops when you get an error

**Comment by bulut-dev** [comment]
https://github.com/TheGameCreators/GameGuruRepo/assets/76091156/c5ece65a-814d-4510-ab5a-193fae7d9001

**Comment by LeeBamberTGC** [comment]
@bulut-dev Looks like a crash of the FPM level rather than a 'black' screen issue. Can you do another video that starts with you clicking the LAUNCH button in the Steam client so I can see the whole process of you getting to load the level, and also attach the level FPM file here if it is using stock media, thanks!

**Comment by bulut-dev** [comment]
https://github.com/TheGameCreators/GameGuruRepo/assets/76091156/8990ccbd-b82d-479d-adc6-6692e595c3d0

   sürücüyü değiştirdim. dosyaları doğrulama yaptım. yinede aynı

**Comment by bulut-dev** [comment]
I don't know how to pull the fhm crash. is it ok if I delete the app and reinstall it?

**Comment by LeeBamberTGC** [comment]
@bulut-dev You do not need to pull anything, just record a video of you loading the FPM and maybe clicking test game until it crashes as you report, so I can see the crash in the video, thanks!

**Comment by LeeBamberTGC** [comment]
Properly fixed now for next EXP build - was RSSetScissorRects and a recent AMD driver update!
