### ISSUE TITLE
GGMAX Bug - Save Standalone Linear Level Linking Breaks Levels

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#5620]
There are numerous issues with the Save Standalone feature, making it impossible to create a functional multilevel game. This was a significant problem in GG Classic and has re-emerged.

Firstly, the "Standalone Test All Levels" mode fails to reflect the actual standalone build accurately. This mode is presumably meant to simulate how a standalone game will play, identifying any issues before the build. However, it does not serve this purpose effectively. When using Standalone Test All Levels, my game plays fine, but once I save a standalone build, the problems start.

Here are some specific issues I've encountered: 

Only the first level runs correctly. Any subsequent levels are severely broken.
Scripts fail to execute, materials and textures do not load correctly on entities, and some entities display incorrect materials/textures.
Emissive textures sometimes fail to render properly.
Random scripts do not function as intended.
Images from the image bank do not display when referenced in scripts.

Additionally, saving and loading the game introduces further complications:

Triggered events, such as water level changes, do not maintain their state after saving and loading.
Enemies set to Not Show At Start, which haven’t spawned yet, inexplicably have collision enabled.
Numerous scripts become non-functional.
Overall, the Save Standalone feature and save/load mechanics are highly unreliable and broken. These issues need to be addressed to ensure the creation of playable standalone games. I'm sure there is many more issues than what is listed above but I can't make it through more than 2 or 3 levels before something is so broken it stops me from continuing. For example one level the Win Zone just doesn't work.

**Comment by Denis87z** [comment]
due to an error in variables, it is not possible to make games with an open world and multiple locations

**Comment by Kitakazi** [comment]
@Denis87z 
Hi Denis87z that might be a different issue than what I am talking about. I'm just talking about a linear game. I have not tried to game any sort of open world game with multiple location. I'm just talking about a linear game with linear level progression. 
Unless your game also works as expected with the Save Standalone Test - and then your game presents the issues once you actually build the game.

**Comment by mike123yy** [comment]
Yeah, this is a pretty big problem. I'm building a linear game myself and it runs fine testing it. As soon as I made it a standalone objects have different textures, scripts don't work, items either gain or lose gravity and just fall all over the place and the save and load function is almost completely broken. If you save the game on standalone when you come back it might take you to the first level once you complete the level you're on or it might not let you beat it at all because zones won't trigger. Pretty much everything you've listed above I've encountered and had a problem with. I sent my game into Lee so he could take a look at the problems but I haven't heard back yet. Hope this gets fixed soon

**Comment by Kitakazi** [comment]
Had typo in title :( just fixed

**Comment by mike123yy** [comment]
The new dev test beta version seems to have fixed the saving and loading issue. I've been working with Lee on my game to get that solved. I noticed a bit of the bugs were gone but there's still some there so you might give the a dev test beta a try and see if it makes a difference. I also gave him a link to this issue so hopefully these issues can get squashed.

**Comment by mike123yy** [comment]
Standalone bug issues specific to my game for Lee:
trigger zones that are hidden until triggered by another zone don't actually get hidden on the majority of them. They trigger immediately when stepped on.

Almost all particles are missing on the stand-alone and reset themselves with the default speed. The speed issue is also present during the testing with the dev test but not the public build.

Cinema guru Max cameras and markers are all visible during gameplay. This might also be an issue with the dev test

enemy characters when triggered make a high pitch crackling sound with the audio until offscreen or killed

wine bottles in my second level have physics set and are affected by gravity but in the stand-alone they just stay in the air and don't move. They function fine during testing.

I will update this if I find anymore.

Like I mentioned in the email if you take any of these individual levels and put them in a standalone on their own the issues go away. As soon as you build the game with all the levels connected problem start happening. At least for the ones I tested.

**Comment by LeeBamberTGC** [comment]
@Kitakazi When thge next EXP build comes out, try your project with it in the Standalone Export mode first to make sure your game works across multiple levels. If you hit a snag, pick out the first one you see and document the step by step, then email me the standalone you exported so I can reproduce following your steps in my debug mode so I can see where it goes wrong. Best to tackle them one by one as I have done with Mike123, and in this way we should resolve all the issues you encounter.

**Comment by mike123yy** [comment]
I don't know why I never considered it but I made a level select menu on my standalone to see if it would make a difference with how the levels load. When using the level select menu if you jump to any level almost every bug is gone. If you play straight through them all the bugs come back. So the main issue here seems to be a bug when linking levels directly together. I thought adding a loading screen between each level might jog its brain but that didn't seem to help. So that has to be where the main problem is coming from. Linking them together how a game should work seems to make them load incorrectly and cause all the bugs. When doing the level select the trigger zones work fine as well as the collision and gravity. My entities that go missing come back and all the camera markers for cineguru don't show after the cinematic is played. The particles didn't come back but I figured that out too. The exporter for the standalone is not exporting the users particles. If you check the user folder after exporting the stand-alone it's empty. If you place them back in manually they show up.

**Comment by LeeBamberTGC** [comment]
As this 'general standalone' issue has a growing list of items being added, reported now by two different users, it is a good idea to break this up into one report for each issue, so we can reproduce each one in turn and work on the fix. I have handed this issue to Kass to help with this, and reproduce the issues with the next DEVTEST.

**Comment by Kitakazi** [comment]
I guess originally the issue was supposed to be that the Standalone Test All Levels 
![image](https://github.com/user-attachments/assets/d9b24937-ba6b-47e9-b99c-1542f043f071)

that this does not accurately represent an actual Standalone Game since numerous things are missing or bugs appear or w/e. But yea I guess that is a blanket kind of report anyway... so would you like me to just close this issue or should I leave it open?

**Comment by mike123yy** [comment]
Hey kitakazi, before you close the issue you might want to try one thing. You said your first level works good but the levels after that have problems. Try making a custom screen and then make a continue button and link that to the next level using the "win level" link instead of the "go to next level" link and do that for every level then see if the issue still happen. When you connect the levels directly to each other it seems to be causing the problem, at least for me. If it's the same for both of us I would say all these issues are from the same single problem. The storyboard isn't loading the following levels correctly when link directly together. That's why the first one always works but the other ones have problems. So you'd want your levels to look like this:
first level – continue screen – second level – continue screen – third level – continue screen – etc.

**Comment by Kasseyus** [comment]
@Kitakazi Hi there.  Now that the EXP build has been updated, would you please try running your standalone build in this version, and if you still encounter issues, can you upload them here, as one issue per ticket.  This will help us to identify, replicate and solve each individual bug.

**Comment by Kitakazi** [comment]
mike123yy is correct. Adding a new screen and having it link to the next screen or level with "win level" fixed a lot of the issues. So yea something is definitely busted with normal way of having a 
LEVEL > LOADING SCREEN > LEVEL. For w/e reason like he said if you connect them that way it there is a lot of problems that arise.

**Comment by Kitakazi** [comment]
@LeeBamberTGC 
Re-opened this one because ALOT, like seriously almost every Save Standalone issue that I think people have is caused by what @mike123yy discovered. Connecting levels with a loading screen on in HUD produces errors in standalone games, but connecting some sort of Continue screen before the loadscreen will actually cause the levels too load in properly with no issues. So yea fixing this would be huuuuuge.

**Comment by Kasseyus** [comment]
@mike123yy @Kitakazi 
Hi Folks.  Can you please E-Mail me your project to chris@thegamecreators.com so I can replicate this issue - we can them work on getting this problem solved once and for all. :)  

It sounds like a  lot  of the issues have a root cause in how the levels are linked, so if we solve that one first, and any bugs listed 
 above that remain can be then identified and resolved individually.

**Comment by mike123yy** [comment]
Are you wanting a standalone with the continue screen between each level that fixes it or the broken standalone that links each level together the traditional way? Lee has all my levels for each but I don't know if you guys share files between each other. I have a standalone already in my Google drive but it's the one that uses a continue screen between each level to get it to work properly. I could send you that one quick but I would have to rebuild the game if you want the messed up version. Let me know which one you need

**Comment by Kasseyus** [comment]
@mike123yy 
Would you be able to send the project files, rather than the exported standalone?

The folder can be found in the writables area, e.g:
C:\Users\...............\Documents\GameGuruApps\GameGuruMAX\Files\projectbank\...........

**Comment by mike123yy** [comment]
They are on the way now =)

**Comment by LeeBamberTGC** [comment]
@Kitakazi @mike123yy I have fixed an issue that shows up in Tom's haunting demo, specifically related to subsequent levels not being in the state they should be. The fix was to clear out some of the LUA global tables that held onto old data and caused all sorts of minor mayhem. Adding the interstitial screen helped clear this data, but not a great solution you will agree. In the next DEVTEST this data is now cleared out so feel free to try making and playing a new standalone with multiple levels.  To keep things clean, this issue will relate to the issue of secondary levels and loaded saved games from being in the wrong state, and when fixed we will close it.  Related or similar issues should be reported as a new clean separate issue so we can knock the bottles down one by one :)

**Comment by mike123yy** [comment]
I seen the update video that said this issue was fixed and that the new update was rolled out today. I put Max back on the retail version and gave the standalone a try. It still isn't functioning properly. I did the test with the new game I'm working on and what I've noticed is the user particles are not being exported with the standalone, weapons don't show up on levels after the first one, some scripts don't function properly unless you reload the level. Basically the stuff that was happening before. I also noticed most everything works good still if you add the continue screen in between the levels but recently I've been seeing a bug or two even with the buffer now. I have a level where you start off in the elevator and after your conversation the elevator doors open on a time to trigger. Going through the levels in order only one of the doors will open and then it gets stuck in a open and closing animation. I added a level select menu to jump through the levels and if you load the level that way everything works fine. Unless the update hasn't been pushed in my time zone yet I think it still needs some work

**Comment by Kasseyus** [comment]
@mike123yy I believe the fix for this bug is still in the DevTest/Experimental branch as it is an open issue in need of confirmation.  If you could run the above test again on the Experimental Build, we can then confirm the bug is fixed, close the ticket as resolved and then this fix will be scheduled as part of the next Retail Build.

**Comment by mike123yy** [comment]
I did an export of my new game as a standalone and it's showing the same problems with the experimental build.  I was trying to do a standalone of the haunting game lee has been working on for reference but it keeps crashing on me when exporting it so I can't confirm the bugs on that one yet.  I will keep trying for that one but with the other game the levels are still not loading properly

**Comment by mike123yy** [comment]
Got a version of the haunting of rosewood game exported to standalone and I can confirm it still broken testing both games. Besides linking the levels directly together I also tried setting the win zone to go to specific levels and not link the levels together at all to see if that would work. Both methods are broken. Whatever's going on with the linking system it loads the first level just fine but then after that something goes wrong. Anyway you arrange the levels the first one always works but then the next ones don't load properly. If you do a level select menu every level works properly from their but that's because it's basically just loading it like the first level and not one after the other. But, either way, it still needs fixing

**Comment by LeeBamberTGC** [comment]
@mike123yy With the latest version I was able to take your demo project and export the standalone with no issues, shot below:
![image](https://github.com/user-attachments/assets/37de92df-212c-40f5-af06-4bd321026703)

The standalone itself seemed to exhibit no issues as I move from the first level to the second, with no CineGuru markers showing and the ball rolling down the stairs as normal. I have emailed you my export, have a play and let me know if you see the same things. Be aware that if you are exporting a new game and running it, best to delete the writables folder called "savegames" as it will contain out-of-date data with respect to the exported game.

**Comment by mike123yy** [comment]
I made your video of me playing your demo on my end so you can see what's happening. The first level works fine so you can skip to three minutes and 40 seconds where the second level starts. The first thing you can notice is that the car doesn't move anymore on your standalone. Once you enter the house everything downstairs works as it should but once you go upstairs the ghost girl is frozen in the hallway and all the triggers activate before they should. Going out on the deck they cult member doesn't move or activate. Once you collect the key and go into the room that trigger goes off before it should and the animation doesn't play for the ghost girl, probably because she's bug out before hand. If you'll notice at the end of the level when you insert the fuse into the box it plays the audio line "whose there" which was never a part of the level. Moving on to the next level you can see that all the custom fog is gone. Once you get down to the first room the lightning doesn't seem to be playing at script correctly. After moving on from that room to the next room on the other side of the level the blood activates before it should and fills up the room before you have a chance to get to the key. It's pretty buggy :-) I did go into all the folders in the documents and delete all the save game folders to see if that made a difference although I think you are just talking about when you export the standalone but It didn't make a difference anyway. If this is playing fine on your end without the stuff happening then I would be stumped as to why my computer doesn't play it correctly. 

https://drive.google.com/file/d/1xuP6lIYIAyYDi_o9fg7vltYrEGLkeE3q/view?usp=sharing
[https://drive.google.com/file/d/1xuP6lIYIAyYDi_o9fg7vltYrEGLkeE3q/view?usp=sharing](url)

**Comment by mike123yy** [comment]
One quick thing I did notice running through my project is that it seems with the ghost girl and the cult member guy somehow the checkbox for them to show at the start of level has been ticked and their scripts needed to be re-loaded onto each of the characters so that's probably not due to the standalone. Probably the same for the lightning. That way if you're trying to figure out why that stuff won't stop bugging out during testing that's the problem. The trigger malfunctions and the other stuff is from the standalone though.

**Comment by LeeBamberTGC** [comment]
@mike123yy Using your video, can you describe in detail the first trigger from your observation that "and all the triggers activate before they should". I believe this is the first of the outstanding issues now we have confirmed the car, girl and other issues are related to level settings and script logic.  Thanks!

**Comment by mike123yy** [comment]
So for the triggers going off wrong the first one would be at around the five minutes and 25 second mark right when I walked past the ghost girl who was frozen in the hallway. That sound is not supposed to play until you go around the corner and trigger the bottles to fall. So how it should play out is you go around the corner and you hear the bottles fall and when you turned back around and looked down the hallway you should hear the boom sound jump scare. The next one is after you collect the keys and go back to the bedroom door you can see me turn around in the video and backup through the door. The boom jump scare that happens there is going off before it should. You are supposed to walk to the window and hear the little girl laugh then collect the key. Once you head out of the room that jump scare is supposed to happen and the little girl is supposed to run past the door. Once you get to the next level that's the dream sequence and you enter the room with the shower where you're supposed to collect the key the trigger that makes the blood fill up the room triggers before it's supposed to. Basically every trigger that has the spawn at start unchecked goes off without having to be triggered.

I noticed with my other game I'm working on that when you export the standalone without the continue scene in between that weapons won't show up in the players hand. also the triggers that control the elevator doors opening and closing work fine when testing the game but in the standalone only one of the doors opens and then it just starts opening and closing continuously. you should have the files for that game too since I sent you everything I had if you want to use that for testing as well. it's called "in black".

The problem with the car/girl/lightning should be from moving the scripts to the documents folder instead of the main folder, at least on my end. I have no idea how their Spawn at start checkboxes got checked again. If you look at those models and they aren't set to hidden until triggered and they still bug out with the standalone that would still be a problem. Some funny stuff happened after my hard drive malfunctioned but the files I sent you were before that so I don't know if there wonky on your end are not. Anyway, I think that about covers it :-)

**Comment by LeeBamberTGC** [comment]
@mike123yy I have uploaded a new DEVTEST that makes some small tweaks and updated the plrinzone script to fix the issue of the spawn at start logic not working properly inside a standalone and when levels are restored.  We can tackle the "weapons won't show up" and other standalone issues once we know we have fixed the trigger zones for standalone :)

P.S. If you can resend me the car/girl/lightning scripts you have, I can improve my own 'demo project' files to get closer to a finished and working version of your project, thanks!

**Comment by mike123yy** [comment]
I sent you those files to your email so you should have them pretty quick. I went ahead and made a stand alone with the first three levels like we've been doing and the trigger zones seem to be functioning like they should now. The entire second level worked and I jumped to the third level and that one didn't have any problems either. All the other stuff seemed to be functioning good as well as far as the haunting one goes so either it's a big coincidence or the zones all seem to be fixed :-) as far as the weapons go I've had them bug out in two different ways. On my other game I have the players start out with a weapon and when the level starts it's not in their hand and I did have one at the end of the haunting game when you fight the woodland demon that the pistol wouldn't ever show up to be able to be collected. I did notice that custom particles made with the particle editor still don't get exported with the standalone but I suppose that's a separate issue anyway but still has to do with the standalone. Anyway, triggers look like they are fixed. Merry Christmas!

**Comment by LeeBamberTGC** [comment]
@mike123yy Preben made some great fixes related to weapons this year, so if you have time, perhaps check to see after some clean up if your project is happy once you remove any weapons you do not need, and they should not reappear in the latest DEVTEST :)

**Comment by mike123yy** [comment]
The problem wasn't with weapons showing up when they weren't supposed to, they weren't showing up in the standalone when I placed them around the level (or in the players' hand unless you added the buffer screen in between).  It still wasn't fixed the last time I checked but I will give it another shot here in a minute and see if it's still there =)

**Comment by mike123yy** [comment]
I already tested before I got the message on the other thread but the good news is all the weapons seem to be showing up now.  So, that's awesome!  I removed the buffer screen as well and they were still working so i supposed we can consider this closed unless kitakazi still has issues.  thanks!
