### ISSUE TITLE
[ISSUE] Shadows Disappear with Camera Override or FreezePlayer

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#642]
When you use the camera override commands the dynamic shadows will disappear. For example shadows cast on the terrain by character will no longer be visible. 

This has impacted two game projects of mine I am moving the camera around via LUA.

**Comment by Teabone3** [comment]
Transporting the player with the freeze commands seems to have the same effect.

**Comment by Teabone3** [comment]
Also.. if you are rotating the camera the shadows will be visible during the rotation but disappear afterward.

**Comment by JCLEONITA** [comment]
yes this happening to me too...

**Comment by Duchenkuke** [comment]
Yes, I can confirm this, thats why I removed the "freezeplayer" part of a script.

**Comment by Kitakazi** [comment]
yep seen this bug for a while now.

**Comment by plemsoft** [comment]
@Teabone3 Thanks for reporting this,

I tried amenmoses boat script that uses:

   SetFreezePosition( x + xo, y + yo, z + zo  )   
   SetFreezeAngle( 0, deg( ya ), 0 )
   TransportToFreezePosition()

But shadows seams to be fine here ?

Is anyone able to make a .fpm that show the problem , and post it here or email it to me at plemsoft@plemsoft.com , i need to be able to reproduce it somehow , thanks :)

![SetFreezePosition](https://user-images.githubusercontent.com/18662417/69974145-ef899a80-1524-11ea-9523-cfc07c286b15.jpg)

**Comment by plemsoft** [comment]
@Teabone3 Do you have a small fpm i can use to debug this ? :)

**Comment by plemsoft** [comment]
No need for a fpm , found it!

Shadows will disappear when using lua FreezePlayer() or anything that disable player logic.

This has been fixed and will be in the next update :)

**Comment by Teabone3** [comment]
Thanks so much @plemsoft  !

**Comment by Teabone3** [comment]
I'm still experiencing shadow's going off and on in the "christmas update". My FPM is however extremely complicated as it has many scripts running with a lot of images and audio attachments. Would be hard to send the whole project. Do we have standalone unencrypted mode?

I'm using camera override commands that might be causing this bug

**Comment by Duchenkuke** [comment]
*Do we have standalone unencrypted mode?*

yes we have! I think you need to do a change in the setup.ini
then gg creates unencrypted standalones

**Comment by Teabone3** [comment]
Here is the video @Duchenkuke did while testing and you can see the shadows disappearing 

https://www.youtube.com/watch?v=Bj3d3Re9eek&lc=z22ygzvjztnmzbfo404t1aokg021vlwufau5kgrlqthxbk0h00410

**Comment by Teabone3** [comment]
I can confirm now that the shadows issue is completely fixed now. Thanks again.
