### ISSUE TITLE
shadows

### ISSUE THREAD

**Issue by earthling45** [TheGameCreators/GameGuruRepo#715]
I've started to make some models for the structure editor which i will forward to you for review and if these models are deemed decent enough they can be added to GGC and GGM.
But when reviewing a first roof model, i've noticed a problem with shadows.
So i've made a little structure with EBE and tested it, the result can be seen in the video and image. :)

![om6ZkRY 1](https://user-images.githubusercontent.com/35744254/77237436-8065ae00-6bc8-11ea-82e5-fdcf0679c063.png)

https://www.youtube.com/watch?v=XvP_CZvmnF8

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
@plemsoft 
Confirmed and tested. Video supplied.

**Comment by plemsoft** [comment]
@earthling45 Thanks for reporting issue, this has been fixed and will be in the next update :)

**Comment by earthling45** [comment]
Thanks Preben. :)

**Comment by LeeBamberTGC** [comment]
@plemsoft I recompiled the shaders, and latest check-in, but the issue remained, see shot below.

![image](https://user-images.githubusercontent.com/35840583/77477253-f742b700-6e13-11ea-848b-c077a7f7a4b4.png)

I have assigned this to be as I suspect it has to do with how the alpha zero pixels are not being clipped out at the shader level. I put a few hours into this last night, but I think I have the solution now...

**Comment by LeeBamberTGC** [comment]
Seems a newly created EBE used the old entity_basic shader, instead of the Better apbr_basic shader which has the correct clipping code for the alpha slice.
