### ISSUE TITLE
Possible Verify bringing up 2 bugs ?

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#777]
@plemsoft 
On the latest 1-5-2020 build I cannot seem to load the CC or load new textures from the .ebe by right clicking ... Not sure if this is just me ?
I have only seen one report so far of the CC not working but it seems to be after a verify.

**Comment by earthling45** [comment]
Confirmed, not just you.
CC does not work and textures are not loaded. :)

**Comment by synchromesh62** [comment]
@earthling45 
Thanks for the conformation
Bug Label added

**Comment by plemsoft** [comment]
@synchromesh62 Thanks for reporting this,

Both issues has been fixed and will be in the next update.

**Comment by LeeBamberTGC** [comment]
Uploaded fixes to the BETA and PP builds on Steam, please check them out and report as fixed here, so we can close this, thanks!

**Comment by synchromesh62** [comment]
Updated and issue fixed. 
Verified and issue still working perfectly.
The Character Creator and the .EBE now seem to work without any issues :)
Excellent Build .. Thanks  @LeeBamberTGC @plemsoft
