### ISSUE TITLE
Black textures in custom terrain, newest PP

### ISSUE THREAD

**Issue by thecyrus** [TheGameCreators/GameGuruRepo#84]
This level was created in previous Public Preview and opened in the new one.
Custom terrain has some black textures. Maybe they're missing?

https://youtu.be/Ennn4AnMopE

**Comment by Teabone3** [comment]
I wonder if that is related to the lightmapper? Or if you change Terrain Shader Quality if it is fixed at all?

**Comment by thecyrus** [comment]
Yes, Medium and Low are ok.

**Comment by GraPhiX-Guru** [comment]
do you have pbroverride=1 or =0 in your setup.ini

**Comment by thecyrus** [comment]
pbroverride=0

**Comment by plemsoft** [comment]
Looks like the PP version you made the level in , did not create the terrain atlas normal map correctly , to fix this , just select your terrain textures again , and save the level.
Let me know if this fix your problem :)

**Comment by plemsoft** [comment]
> pbroverride=0
> 
> I need it, because if it's set to 1 many existing models have black textures.

This has also been fixed in my latest branch , so you dont get the black textures using pbroverride=1.

**Comment by tarkus1971** [comment]
pbroverride = 1

 i am still getting black textures on lots of assets, stock and purchased, valuable asset buildings especially.

**Comment by plemsoft** [comment]
Hi Tarkus :)

This has not been released yet , and are not in the current PP version , next time PP is updated it will be included :)
