### ISSUE TITLE
runtime error 8003

### ISSUE THREAD

**Issue by bluemeenie195** [TheGameCreators/GameGuruRepo#875]
Hi Guys,

Having trouble getting Max to work.

I first installed it on my D drive ( where I want it to go ). Once installed with no problems I clicked on the launcher app and nothing happened.
I uninstalled it and reinstalled it where the tiny installer wanted to put it ( on my C drive ). Nothing happened. Just a quick white screen then nothing.

I have a  I 9 intel chip with a RTX 2070 with 16 gigs of ram, with 2 TB of space.

The other Alpha's worked fine.

I uninstalled it and reinstalled it again on my D drive then I got no path found, and runtime error 8003
![Screenshot (13)](https://user-images.githubusercontent.com/75592663/106407686-b25fb780-640a-11eb-825c-b5e1d9df0bb9.png)
![Screenshot (14)](https://user-images.githubusercontent.com/75592663/106407693-b5f33e80-640a-11eb-8cee-03f3337f820e.png)
![Screenshot (15)](https://user-images.githubusercontent.com/75592663/106407700-b8ee2f00-640a-11eb-8847-13634ba11af3.png)

**Comment by LeeBamberTGC** [comment]
Please attach your "Guru-MapEditor.log" file which can be found in your "C:\Users\<YourName>\Documents\GameGuruApps\GameGuruMAX" folder, thanks.

**Comment by bluemeenie195** [comment]
It gives me no Guru-MapEditor.log after I try to launch the Max app and then gives me the 8003 error code.

What's weird is I tried it on 2 other computers I have. One on the C drive and the other on the D drive, installing it the exact same way with no problems.
Only on my main computer it won't work.

![Screenshot (19)](https://user-images.githubusercontent.com/75592663/107389682-fe72c200-6ac4-11eb-8cb3-818adb86d3a0.png)

**Comment by GraPhiX-Guru** [comment]
maybe a long shot but are you using OneDrive ? or is OneDrive backing up your documents, pictures etc.. automatically ?

if so turn it off so you can test, i believe the issue is down to your documents folder being virtual i.e constant synching with OneDrive

**Comment by bluemeenie195** [comment]
OneDrive is turned off.
I don't use it

**Comment by bluemeenie195** [comment]
There was another person on the forums that has the same issue.
I might have a log file

**Comment by GraPhiX-Guru** [comment]
i would double check that because your screen shot shows onedrive with folders in it !

**Comment by bluemeenie195** [comment]
I just did.
It just asked me to log back in to sync.

**Comment by bluemeenie195** [comment]
With the 
[install_errors.txt](https://github.com/TheGameCreators/GameGuruRepo/files/5975864/install_errors.txt)
new updater

**Comment by LeeBamberTGC** [comment]
Should be fixed for this Fridays build!

**Comment by bluemeenie195** [comment]
Great ! Thank you

**Comment by bluemeenie195** [comment]
Just downloaded the new update from 2/19.

Unfortunately still does not work for me.

I did a verify and it said had all the files.

**Comment by LeeBamberTGC** [comment]
Could you send a small video showing what happens when you successfully complete the verification process in the updater and launch MAX, thanks!

**Comment by bluemeenie195** [comment]
https://user-images.githubusercontent.com/75592663/108711842-edbe4500-74e3-11eb-9268-0adde09a9871.mp4

**Comment by bluemeenie195** [comment]
That's after verifying the files and saying it's good

**Comment by LeeBamberTGC** [comment]
Thanks, thats just what we needed. Looks like an instant crash out. Can you send me the "Guru-MapEditor.log" file that was produced in the "\Documents\GameGuruApps\GameGuruMAX" folder after the crash?  Also, can you confirm that you have any enhanced modes on your sound devices deactivated. We had a recent report of a sound card enhancement mode causing the sound files not to load in MAX.

**Comment by bluemeenie195** [comment]
![Screenshot (21)](https://user-images.githubusercontent.com/75592663/108716339-fa459c00-74e9-11eb-8f35-88d9d2659217.png)
That's the problem. It doesn't give me any crash log.

When you go to GameGuruApps then to the GameGuruMax folder, there is nothing there at all. No folders or anything.

**Comment by LeeBamberTGC** [comment]
That is interesting. No files at all suggests the main EXE binary is really failing fast.  Can you show me the installation folder, ie: "C:\Program Files\GameGuruMAX" and the folder inside that: "C:\Program Files\GameGuruMAX\Max". Also, zip up and attach the "GameGuruMAX.exe" found in the subfolder, thanks!

**Comment by bluemeenie195** [comment]
![Screenshot (22)](https://user-images.githubusercontent.com/75592663/108718555-8d7fd100-74ec-11eb-9353-74be4e711846.png)
![Screenshot (23)](https://user-images.githubusercontent.com/75592663/108718559-8fe22b00-74ec-11eb-98c4-e85246ab6df1.png)

**Comment by LeeBamberTGC** [comment]
Also, zip up and attach the "GameGuruMAX.exe" found in the subfolder, thanks!  MIght be worth checking at your own risk if any virus checker are interrupting the execution of the EXE, and also try installing to the C drive where Program Files traditionally goes.

**Comment by bluemeenie195** [comment]
[GameGuruMAX.zip](https://github.com/TheGameCreators/GameGuruRepo/files/6022933/GameGuruMAX.zip)

**Comment by bluemeenie195** [comment]
I did have Norton that I completely removed from my computer and I tried installing in multiple places with no luck.

**Comment by bluemeenie195** [comment]
![Screenshot (24)](https://user-images.githubusercontent.com/75592663/108730983-15b8a300-74fa-11eb-8f1d-3c6e0f2c4f6a.png)
That's weird, Max doesn't even show up in the Windows Defender app list

**Comment by bluemeenie195** [comment]
Don't know if you can do this yet, but would it be possible to give me the code to download through Steam and see if it works ?

**Comment by LeeBamberTGC** [comment]
MAX is not available through Steam. Can you delete the "\Documents\GameGuruApps" folder and see if running GameGuruMAX.exe recreates it?

**Comment by bluemeenie195** [comment]
It did not recreate the folder

**Comment by LeeBamberTGC** [comment]
It could be that Windows defender is not letting it through. Can you rename the EXE and see if you can add it to the Defender White List?

**Comment by bluemeenie195** [comment]
Do you mean the launcher app exe ?

**Comment by LeeBamberTGC** [comment]
I mean this one: "C:\Program Files\GameGuruMAX\Max\GameGuruMAX.exe"

**Comment by bluemeenie195** [comment]
I renamed it GameGuruMAX2 and double clicked on it then checked the defender list. still nothing.

**Comment by bluemeenie195** [comment]
So I uninstalled it again and put it back on my C drive, then I added the EXE manually to my windows defender to let the app through and still nothing.

I don't get it.
![Screenshot (25)](https://user-images.githubusercontent.com/75592663/108883845-ed04dc00-75d3-11eb-9e57-470c386c937b.png)

**Comment by bluemeenie195** [comment]
Don't know if this will help, but when it gives me the error message the regular GG map editor app shows up.
![Screenshot (26)](https://user-images.githubusercontent.com/75592663/108884439-9d72e000-75d4-11eb-90a2-547af1812f71.png)

**Comment by LeeBamberTGC** [comment]
The second shot looks like the old GameGuru Classic MapEditor icon. Are you sure you got this when you ran GameGuruMAX.exe?

**Comment by bluemeenie195** [comment]
I know it's weird.
Unfortunately I'm at work right now, but I will try to make that happen again and show it on a small video clip.

**Comment by bluemeenie195** [comment]
GameGuru Classic MapEditor icon pops up when I double click the Max launcher app



https://user-images.githubusercontent.com/75592663/109905664-217c3600-7c6d-11eb-8b56-9a03bd5ddc1d.mp4

**Comment by bluemeenie195** [comment]
2021.03.05 update worked for me.
Max is running now.

Thank You guys

**Comment by LeeBamberTGC** [comment]
Good to hear, thanks for letting us know!
