### ISSUE TITLE
Normals Broken - In New Repo

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#984]
Normals are all over the place for my models - previous build they were fine in all locations and angles - I think it is related to light from outside interior models tho?

But I probably wrong :)

Picture:
![FlippingNormals](https://user-images.githubusercontent.com/12246318/111140410-68a3e880-85d6-11eb-9195-0f8cf9de041e.png)

Same wall in Classic shows how they should look:
![Rach Sign](https://user-images.githubusercontent.com/12246318/111141949-3a270d00-85d8-11eb-8301-bc2527494fdb.jpg)

System Specs:
None detected!

**Comment by rvanner** [comment]
@LeeBamberTGC Additional info from your task report on Teamwork;

Normals are all over the place for my models - previous build they were fine in all locations and angles - I think it is related to light from outside interior models tho – but I probably wrong 😊

Unwanted capsule of light following the player
Video example: https://vimeo.com/520226444/1570f969f3

**Comment by michaeloldman** [comment]
Build 2021.02.04 - Exhibits same issue :)

**Comment by plemsoft** [comment]
@michaeloldman Could be light from the outside, perhaps it has to do with single sided triangles ? , could you try the "double-sided" trick and check if the normals look fine , thanks for your help :)

**Comment by michaeloldman** [comment]
@plemsoft 
Not seeing this issue on walls now. 

Only seams to be on floors. The models have an exterior section too (separate model) so should be blocking light?
Tried the double sided trick on all meshes of this interior model but makes no difference. 

Please note these are models converted by MAX at startup.
I am thinking it maybe a combination of Assimp (doesn't seam to like models exported from blender) and also when lights are used close to the floor.

Some pics:
![normals not correct in some areas](https://user-images.githubusercontent.com/12246318/117438054-64f86680-af74-11eb-8275-8890639f9abf.png)

![Normals - messed by lights](https://user-images.githubusercontent.com/12246318/117438106-73468280-af74-11eb-8959-408a7e24549e.png)

Thanks for looking into it.

**Comment by michaeloldman** [comment]
I think this is related to Lighting somehow for the most part. Turning down the normals strength makes little difference, and making double-sided also makes no difference.

Just a reminder: none of these issues were present at all before the first wicked-repo.

**Comment by plemsoft** [comment]
@michaeloldman The only way at the moment to stop normals (light) from outside , is to turn down metalnees on objects to 0, or set the sun color (Lightning Color) to black. if you set sun color to black you will have no light on the normals from outside.

https://drive.google.com/file/d/19i_ge0dAmjT_mXZ3FX7xcJd7w_2NPGc1/view?usp=sharing

**Comment by michaeloldman** [comment]
@plemsoft - Those tricks do not work for me.
In the above screenshots the Lighting Color is already Black. 
Also tried turning metalness to zero and does not make ant difference.

Might be best if I create a scene that shows the issue and email it for you to test your end. If it can be fixed in one area it should carry through to other areas as well.

**Comment by plemsoft** [comment]
@michaeloldman That would be great, i have nothing to compare with :)

**Comment by michaeloldman** [comment]
@plemsoft Email sent :)

FYI:
The floors in the cross junction where the player marker is, are an example of how the should render everywhere.
Most of the issues in previous pics are evident in other areas particularly where lights are placed, the issue with walls in opening pic are obvious in all areas in the room with only two lights in it.

Scene was a pain to create - lights kept jumping out of place if clicked from above to edit. Seam to be OK if you maneuver camera to below them before clicking, but not always.

Hope that helps :)

**Comment by rvanner** [comment]
@michaeloldman Is this still an issue for you?

**Comment by plemsoft** [comment]
@michaeloldman I remember we fixed this with you sometimes back, is this ready to be closed ? :)

**Comment by michaeloldman** [comment]
@plemsoft 
No normals still have issues for my models. 
In early builds all the normals were perfect, but since the repo and especially since fully utilising ASSIMP they no longer work

MAX no longer likes mirrors it seams (most of Racha models use them).

So I have resigned to the probability it is just my models, and will likely have to bin them and start from scratch. :)

**Comment by michaeloldman** [comment]
Here be couple pics in latest build.
![Max Normals 01](https://user-images.githubusercontent.com/12246318/130224327-a1929ecf-d4e0-42ff-972f-61909fbbfb7f.png)
![Max Normals 02](https://user-images.githubusercontent.com/12246318/130224423-7ea9c11a-b9d5-45ad-abaa-76bdd0470af7.png)

Issues here are subtle - but noticeable.

I uploaded a demo for rick some time back - which is the level those shots are from.

**Comment by michaeloldman** [comment]
Here be a pic in current build 2021.08.20
![Normals Issue 2021 08 20](https://user-images.githubusercontent.com/12246318/130353324-41d8fb83-8a14-4ed5-9217-73ae37356755.png)
